### DISCUSSION TITLE
How do I use escape curly brackets in template?

### DISCUSSION THREAD

**Discussion by budimanjojo** [twpayne/chezmoi#1706] [Q&A] [answered]
Hello, I want to template my `chezmoi.yaml` file but there's one thing that I just can't figure it out. I want to template my config file like this:
```
merge:
  - command: nvim
    args:
      - -d
      - "{{ .Source }}"
      - "{{ .Destination }}"
      - "{{ .Target }}"
```
But apparently chezmoi will assume those args are template variables so it just print out `<no-value>` in the templated config file. Now, how can I do this? Thank you.

**Comment by twpayne** [comment, marked as answer]
The easiest way is:

```
{{ "{{" }} ... {{ "}}" }}
```

but you can put more inside the quotes, for example:

```
merge:
  - command: nvim
    args:
      - -d
      - "{{ "{{ .Source }}" }}"
      - "{{ "{{ .Destination }}" }}"
      - "{{ "{{ .Target }}" }}"
```

**Reply by budimanjojo** [reply]
Wow it works, thanks!!

**Reply by okletzmayr** [reply]
Hey there! First I want to express my gratitude for creating and maintaining this great tool. :heart:

I just ran into the same issue after creating `.chezmoi.toml.tmpl` according to the [docs](https://www.chezmoi.io/docs/how-to/#create-a-config-file-on-a-new-machine-automatically). Would you be open to document this? I only noticed after my neovim diffs got all messed up. 😅 

By the way, before checking GitHub for a related Issue, I solved it [like this](https://pkg.go.dev/text/template#hdr-Examples) on my end:
```
[diff]
    command = "nvim"
    args = ["-d", "{{`{{ .Destination }}`}}", "{{`{{ .Target }}`}}"]

[merge]
    command = "nvim"
    args = ["-d", "{{`{{ .Destination }}`}}", "{{`{{ .Source }}", "{{ .Target }}`}}"]
```
(in case someone wants a copy&paste ready toml format)

**Reply by sandipb** [reply]
Technically, you only need to do `{{ "{{" }}`. The end braces don't need to be escaped if you quote the start braces.

Will reduce the spaghetti of braces in your templates a bit.

**Reply by jvtrigueros** [reply]
It took me a bit grok what @sandipb meant by _"only need to..."_, so to be explicit I believe this is what they mean:
```toml
[merge]
  command = "nvim"
  args = ["-d", "{{ `{{` }} .Source }}", "{{ `{{` }} .Destination }}", "{{ `{{` }} .Target }}"]
```

I opted for backticks to further differentiate, the additional quotes were confusing me. Anyway, thank you for the tip! Super helpful.

**Reply by twpayne** [reply]
Thanks @jvtrigueros, I didn't realize that you could use "`" in templates.

Another option, which may be more or less readable, is to make more of string a literal, e.g.

```
[merge]
   command = "nvim"
   args = ["-d", "{{ `{{ .Source }}` }}", "{{ `{{ .Destination }}` }}", "{{ `{{ .Target }}` }}"]
```

This keeps the quotes and the brackets balanced.

**Comment by mkobit** [comment]
Another alternative that might work for some is using the [`delimiters` directive](https://www.chezmoi.io/reference/templates/directives/#delimiters). This changes the template tags for the file (e.g., to `[[` and `]]`), allowing you to use `{{` and `}}` as literal text without escaping.
Add this comment to the top of your config file template:

```yaml
# chezmoi:template:left-delimiter="[[" right-delimiter=]]
merge:
  command: nvim
  args:
    - -d
    - "{{ .Source }}"
    - "{{ .Destination }}"
    - "{{ .Target }}"
```

If you need to use actual template variables elsewhere in the file, use the new delimiters:

```yaml
[[ .chezmoi.homeDir ]]
```
