### DISCUSSION TITLE
Question - How do you provision your personal computer ?

### DISCUSSION THREAD

**Discussion by bgaillard** [twpayne/chezmoi#1733] [General]
## What exactly are you trying to do?

Hi, first thank's a lot for this great tool ! 

This issue is not directly linked to `chezmoi` but I decided to open it here because i'm sure several users would be able to help (do not hesitate to close this issue if you think it's definitely not the right place to open it).

I'm using `chezmoi` since several months and i'm happy with it to manage my dot files. This is great tool to quickly get my configuration files when i'm installing a new computer, ok for this part.

But when my dot files are successfully imported the applications I used to have on my personal laptop still have to be installed (and the list of the apps to install can be very long). I'm looking for an **easy solution** to provision all the apps I use on a new machine **very quickly**. 

Ideally when I setup a new machine I would like to be able to execute only few commands to have all my dot files and applications installed.

1. Install `chezmoi` and pull my dot files (ok for this part)
2. Get a configuration file (for example a YAML file) which describes what are all the applications I'm used to have. Have a tool to read this configuration file and provision all those applications in one shot

For example we could have a YAML file which looks like this one (it's only an example and the format is obviously not "very well-designed").

```yaml
# Languages to install
languages:
    python:
        version: 3.9
    go: 
        version: 1.17.3
        
# Packages to install
packages:

   # Package to be installed with Debian 'apt'
    apt:
        - alsa-utils
        ...
        - xorg
        
    # Packages to be installed with Python pip
    python:
        - aws-shell
        
    # Packages to be installed with custom provisioners
    custom:
        - terraform
```

This YAML file would allows to describe the following stuffs.

- Which languages to install (useful for developers)
- Which standard distro packages to install
- Which "other kind of packages" to install, for example Python, Go, Rust, Docker, Podman, Snap packages

Ideally "the tool", let's assume we name it `thetool` would be

- simply called with the configuration file : `thetool -f config.yaml`
- a simple binary (created in Go or Rust for example) with no complex setup (only the binary + the `config.yaml` file would be required to use it).

Do you know any tool which allows to do that ? If not how do you re-install your computers to not lost all the apps you're used to install ?

## What have you tried so far?

For now I started to develop custom bash scripts which can be easily pulled on a new machine. It works well but it's a custom made solution and is not shared with the community.

## Where else have you checked for solutions?

I searched on Internet but did not found any **simple solution** for a **personal computer** (most of the tools are dedicated to server provisioning).

- We can think about server provisioning solutions but I've the feeling they are too flexible and overkill : Ansible, CFEngine, Salt, Puppet, Terraform, etc.
- [Top 6 Open Source Linux Server Provisioning Software](https://www.cyberciti.biz/tips/server-provisioning-software.html)

**Comment by twpayne** [comment]
Personally I use a provisioning script ([Linux](https://github.com/twpayne/dotfiles/blob/master/home/.chezmoiscripts/run_once_before_10-install-packages-linux.sh.tmpl) and [macOS](https://github.com/twpayne/dotfiles/blob/master/home/.chezmoiscripts/run_once_before_10-install-packages-darwin.sh.tmpl)), and have [similar approaches for Windows](https://github.com/spf13/dotfiles/blob/main/run_once_before_install-packages-windows.bat.tmpl) elsewhere.

**Reply by bgaillard** [reply]
Thanks for your response @twpayne and thanks for sharing your scripts :+1: 

I did not read `chezmoi` documentation thoroughly enough because I did not know we could chain several scripts as you did.

After much more research I think what i'm looking for does not really exist but there's probably good reasons. What I'm thinking about would probably not be flexible enough.

For example in your scripts you install `eksctl` with those commands.

```bash
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
eksctl completion zsh | sudo tee /usr/local/share/zsh/site-functions/_eksctl > /dev/null
```

A "perfect world" would only require to add this in a yaml file and it would be transparent to the user.

```yaml
packages:
    # Packages to be installed with custom provisioners
    custom:
        - eksctl
```

If i've time and it appears it could be useful to the community i'll try to develop a proof of concept.
