### DISCUSSION TITLE
How to make specific content of archive in `chezmoiexternal` executable?

### DISCUSSION THREAD

**Discussion by latipun7** [twpayne/chezmoi#1804] [Q&A] [answered]
If https://github.com/Schniz/fnm/releases/download/v1.29.1/fnm-linux.zip contain `fnm` file, but it does not executable, how to make it executable?

Tried this:
```yml
.fnm:
  type: archive
  url: https://github.com/Schniz/fnm/releases/download/v1.29.1/fnm-linux.zip
  executable: true
```
but it didn't work. 

Tried to change with `chmod` script, but it always tried to overwrite whenever I run `chezmoi apply` because the diff always different.

Please help. Thank you.

**Comment by twpayne** [comment]
`executable` only applies to externals of type `file`. You're specifying an `archive`.

**Reply by latipun7** [reply]
so, is it not possible now?

**Reply by twpayne** [reply]
You can write a script to install `fpm` on your machine, instead of using a chezmoi external. Currently you can't use a chezmoi external because `fpm` is only distributed in `.zip` archives, which require random access to unpack.

I suggest asking the creators of `fpm` to distribute their software in `.tar` format, which can be unpacked with only serial access. This would enable the use of an external filter.

**Reply by latipun7** [reply]
> You can write a script to install `fnm` on your machine, instead of using a chezmoi external. 

Right, maybe that's the best solution for now.

---
> This would enable the use of an external filter.

About filter, I still don't understand how to use it, since the docs are still confusing to me.
> _"If optional string filter.command and array of strings filter.args are specified, the the file or archive is filtered by piping it into the command’s standard input and reading the command’s standard output."_

Can I have any example for better explanation? Thank you.

**Comment by felipecrs** [comment, marked as answer]
Use `zcat`, example:

```yaml
".deno/bin/deno":
  type: file
  url: "https://github.com/denoland/deno/releases/download/v1.17.2/deno-x86_64-unknown-linux-gnu.zip"
  executable: true
  filter:
    command: zcat
```

**Reply by twpayne** [reply]
Thank you, this is the correct answer. Note that `zcat` works on `.zip` files on Linux but not on macOS, but this does answer the OP's question.

**Reply by latipun7** [reply]
Thank you. This is simplify my life 🎉

**Reply by felipecrs** [reply]
Well, there is another option as well which should work on macOS too and may be even more optimized (despite I didn't benchmark):

```yaml
".deno/bin":
  type: archive
  url: "https://github.com/denoland/deno/releases/download/v1.17.2/deno-x86_64-unknown-linux-gnu.zip"
  # PS: do not use "exact: true"
```

The binaries in the archive will already have executable permission, so there is no need to change their permission. If this is not the case, chances are that the archive should be fixed in the source (which would demand to open an issue against its project or something like that).

Remember that in both cases, you need to trust the contents of the archive. For `zcat`, if there is more than one file in the archive, I don't know what would happen. For the `archive` method, if there are more files in the archive, these files would also get extracted (and never removed if they later change because of the lack of `exact: true`).

If the archive was `.tar.*`, you would have more control over what files to take, e.g.:

```yaml
".local/bin/shellcheck":
  type: file
  url: "https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz"
  executable: true
  filter:
    command: tar
    args: ["-xJOf-", "shellcheck-v0.8.0/shellcheck"]
```

This would only install the `shellcheck` binary from its archive, even though there are more files there.

Perhaps a new option could be added to chezmoi to help filter the files in a more abstracted way (thus allowing the same in `.zip` files regardless of the platform). Something like:

```yaml
".local/bin":
  type: archive
  url: "https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz"
  # If not specified, all files are taken
  files:
    - shellcheck-v0.8.0/shellcheck
```

Unfortunately, `.chezmoiignore` would not work very well here because the contents of the archive are potentially unknown and other contents of `~/.local/bin` are also potentially unknown.
