### DISCUSSION TITLE
.oh-my-zsh/cache/completions has changed since chezmoi last wrote it [overwrite,all-overwrite,skip,quit]?

### DISCUSSION THREAD

**Discussion by Syzygianinfern0** [twpayne/chezmoi#1935] [Q&A] [answered]
I've just started using chezmoi and I have this in my `.chezmoiexternal.toml`

```toml
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
```

Every time I make any changes and run the `chezmoi apply` command, I always get this

```
❯ chezmoi apply
.oh-my-zsh/cache/completions has changed since chezmoi last wrote it [overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/cache/grep-alias has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/internal/configure.zsh.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/internal/icons.zsh.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/internal/parser.zsh.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/internal/worker.zsh.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
.oh-my-zsh/custom/themes/powerlevel10k/powerlevel9k.zsh-theme.zwc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? o
```
