### DISCUSSION TITLE
How to change the diff program properly?

### DISCUSSION THREAD

**Discussion by k4leg** [twpayne/chezmoi#2097] [Q&A]
`~/.config/chezmoi/chezmoi.yaml` file source:

```yaml
diff:
  command: difft
  args:
    - --color
    - always
    - --missing-as-empty
    - --skip-unchanged
```

But this config doesn't use pager, and if I add next line to config (or if I use `--pager` option):

```yaml
  pager: less
```

then pager show no diff, or partial diff if I use `less -X` instead of `less`.

Btw, diff program doesn't see scripts like `run_after_blablabla.sh`.  If I specify `echo` instead of `difft`, then I won't see the scripts.

Additional info:

- `difft` is difftastic
- chezmoi 2.17.0

**Comment by twpayne** [comment]
The problem here is that difftastic includes its own pager and it does not seem possible to disable it. When difftastic's builtin pager is combined with `less`, the output is lost.

A work-around is to use `cat` instead of `less` as the diff pager, for example:

```yaml
diff:
  command: difft
  args:
    - --color
    - always
    - --missing-as-empty
    - --skip-unchanged
  pager: cat
```


> Btw, diff program doesn't see scripts like `run_after_blablabla.sh`. If I specify `echo` instead of `difft`, then I won't see the scripts.

Scripts are included in the diff output (unless you explicitly exclude them by setting `diff.exclude`). It's possible that difftastic does not display them however.
