### DISCUSSION TITLE
chezmoiexternal template stopped working

### DISCUSSION THREAD

**Discussion by pirivan** [twpayne/chezmoi#2416] [Q&A] [answered]
I have a simple `.chezmoiexternal.yaml.tmpl` template that has been working fine for some time already. However, it seems to have stopped working lately despite not having modified its source. The template file is ignored when trying to set up a new laptop (`chezmoi` does not update the cache), and running `chezmoi --refresh-externals apply` or `chezmoi --refresh-externals=always apply` does nothing on the laptop where I had the externals previously loaded. Running the commands with `--debug` doesn't show even an attempt to read the externals template.

This seems to be happening since I lately upgraded `chezmoi`. 

Has anyone noticed something similar?

Thank you.

---

My setup:  macOS 12.6 x86_64

```
✗ chezmoi --version
chezmoi version v2.24.0, commit 72d9846a7ae51fd3398727d48815fc2f13a681f9, built at 2022-09-25T17:18:10Z, built by Homebrew
```

```
✗ chezmoi execute-template < home/.chezmoiexternal.yaml.tmpl

.oh-my-zsh:
  type: archive
  url: 'https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.oh-my-zsh/custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: 'https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
```
