### DISCUSSION TITLE
How to get rid of percentage sign from template execution?

### DISCUSSION THREAD

**Discussion by dhruvinsh** [twpayne/chezmoi#2491] [Q&A] [answered]
```bash
> chezmoi execute-template '{{ (output "hostnamectl" "--json=short" | mustFromJson).Chassis -}}'
vm%  
```
When I execute above template on one of the VM I get vm%, how can I get rid of the percentage sign here? 

Because with % sign, `chezmoi init` doesn't work and gives error like `chezmoi.toml.tmpl: toml: incomplete number`

I tried but still the same.
```bash
chezmoi execute-template '{{ trimSuffix "%" (output "hostnamectl" "--json=short" | mustFromJson).Chassis -}}'
vm%
```
at this point I am not sure if % is line ending, but not sure. 

This config is not working for me. 
```toml
{{/* chassisType variable set to "desktop" or "laptop" or "vm" */}}
{{- $chassisType := (output "hostnamectl" "--json=short" | mustFromJson).Chassis }}

[data]
  chassisType = {{ $chassisType }}
```

Update:
found the solution
```toml
{{/* chassisType variable set to "desktop" or "laptop" or "vm" */}}
{{- $chassisType := (output "hostnamectl" "--json=short" | mustFromJson).Chassis }}

[data]
  chassisType = {{ $chassisType | quote }}
```

**Comment by bradenhilton** [comment]
Doesn't the percent sign just signify the end of the output? https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol

What are the contents of the config template?

**Reply by dhruvinsh** [reply]
just updated the main issue for the same. I am not sure what I am doing then but not able to get it work

**Reply by dhruvinsh** [reply]
well this solves the issue.
https://github.com/twpayne/chezmoi/issues/1769#issuecomment-1000281656
I am missing `quote` at the end

```toml
  chassisType = {{ $chassisType | quote }}
```

**Comment by halostatue** [comment, marked as answer]
The `%` is not part of the output.

You need to do one of the following:

```toml
{{/* chassisType variable set to "desktop" or "laptop" or "vm" */}}
{{- $chassisType := (output "hostnamectl" "--json=short" | mustFromJson).Chassis }}

[data]
  chassisType = {{ $chassisType | quote }}
```

or

```toml
{{/* chassisType variable set to "desktop" or "laptop" or "vm" */}}
{{- $chassisType := (output "hostnamectl" "--json=short" | mustFromJson).Chassis }}

[data]
  chassisType = "{{ $chassisType }}"
```

You can see the difference here (I don’t use Linux, so I don’t have `hostnamectl`): 

```console
$ chezmoi execute-template '{{ (output "echo" "{\"Chassis\": \"vm\"}" | mustFromJson).Chassis  }}'
vm%
$ chezmoi execute-template '{{ (output "echo" "{\"Chassis\": \"vm\"}" | mustFromJson).Chassis  | quote }}'
"vm"%
```

Under fish, this looks like:

```console
$ chezmoi execute-template '{{ (output "echo" "{\"Chassis\": \"vm\"}" | mustFromJson).Chassis  }}'
vm⏎

$ chezmoi execute-template '{{ (output "echo" "{\"Chassis\": \"vm\"}" | mustFromJson).Chassis | quote }}'
"vm"⏎
```

Fish is using `⏎` instead of `%` to mean the same thing.

**Reply by halostatue** [reply]
TOML doesn’t allow bareword values for keys:

```toml
[data]
  chassis = vm # ❌
```

vs

```toml
[data]
  chassis = "vm" # ✅
```
