### DISCUSSION TITLE
Are there any usage examples of chezmoi on CI?

### DISCUSSION THREAD

**Discussion by danielo515** [twpayne/chezmoi#2626] [General]
As ridiculous it may sound, I want to add some testing to my dotfiles, and because I use chezmoi to manage them, then I want to use chezmoi on CI 😄 
I tried some naive approaches, but, despite being able to just install chezmoi right, I can't properly execute it. Are any examples out there of people using chezmoi during CI?

**Comment by twpayne** [comment]
> I tried some naive approaches, but, despite being able to just install chezmoi right, I can't properly execute it.

You need to provide more information than just "I can't properly execute it".

**Reply by danielo515** [reply]
yeah, sorry for my vague question. I was just thinking if someone that is already doing it could chime in and just explain their way. It is probably some issue about persistence between job steps, the reported install chezmoi path is not then usable in the next steps: https://github.com/danielo515/dotfiles/actions/runs/3703182094/jobs/6274320843#step:6:8

**Reply by twpayne** [reply]
You install chezmoi in `./bin/chezmoi` and then try to run it from `./.bin/chezmoi`. Did you even read the error message?

**Reply by danielo515** [reply]
> Did you even read the error message?

Yes, of course I did, sorry if it looks like I didn't put care on this. I'm a bit forgetful and this kind of little details usually don't caught my eye. I think I already fixed that detail

I ensured to install chezmoi at a know location, but I still can't get it work between steps:

```
      - name: Install chezmoi
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- -b $HOME/bin init --source $GITHUB_WORKSPACE
      - name: Apply my config
        timeout-minutes: 1
        run: $HOME/bin/chezmoi apply 
```

The reported install location seems correct:

```
info found version 2.27.3 for latest/linux/amd64
info installed /home/runner/bin/chezmoi
```

And it seems to run now, but is not able to find the config:

```
chezmoi: stat /home/runner/.local/share/chezmoi: no such file or directory
```

Not sure if that is the install script is not able to handle bot the `-b` and flag the `init` command, if the github filesystem is not persisting it or something else.

I just want to emphasise that I was just looking for examples of other people using chezmoi in this scenario, it was not my intention to ask anyone to debug my specific configuration.

**Comment by danielo515** [comment]
I think I got it working like this (reduced version):

```yaml
name: CI-dots
env:
  GITHUB_USERNAME: "${{ github.actor }}"
on:
  push:
    branches:
      - master
jobs:
  unixish:
    name: ${{ matrix.os }} ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-20.04
            os: linux
          - runner: macos-12
            os: osx
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - name: Install chezmoi
        run: |
          sh -c "$(curl -fsLS chezmoi.io/get)" -- -b $HOME/bin 
      - name: Apply my config
        timeout-minutes: 1
        run: |
          $HOME/bin/chezmoi init --source $GITHUB_USERNAME --apply
```
