### DISCUSSION TITLE
Using emacs ediff for diff & merge

### DISCUSSION THREAD

**Discussion by J-Kappes** [twpayne/chezmoi#2837] [Q&A] [answered]
Can it be done? It seems to require passing in lisp code to emacs [in single quotes](https://emacs.stackexchange.com/questions/3618/launch-emacs-with-ediff-files-of-ediff-directories-from-command-line). Single quotes disappear if not escaped whereas escaping them yields an invalid toml file.
```
[diff]
    command = "emacsclient"
    args = ["--eval", "'(ediff-files \"{{ .Destination }}\" \"{{ .Target }}\")'"]
```

**Comment by twpayne** [comment, marked as answer]
You don't need the single quotes, i.e. this should work:

```toml
[diff]
    command = "emacsclient"
    args = ["--eval", "(ediff-files \"{{ .Destination }}\" \"{{ .Target }}\")"]
```

Single quotes are needed when invoking `emacsclient` from the shell to stop the arguments splitting on spaces, but chezmoi passes the argument directly.
