### DISCUSSION TITLE
Building dotfiles with GitHub Actions

### DISCUSSION THREAD

**Discussion by bytebone** [twpayne/chezmoi#2951] [Q&A] [answered]
Hello all,

after setting up chezmoi for all the different devices I use, I'm convinced I'll stay with it for the coming future. These config files contain not only my theme for my Linux desktop, but also some (not secret, but theme-unrelated) configs for servers and work devices. I would like to share my desktop theme, based on these files, but not the entire repo with all that unrelated content.

I was thinking that something like this should be achievable with GitHub workflows. Sadly, I'm very unfamiliar with writing those, so I wanted to reach out and ask for community input on how to write this. The flow I was imagining goes like this:

- The workflow is on the main, private `dotfiles` repo and gets triggered on push to that repo
- When a push occurs, it spins up a VM, installs chezmoi, inits from the repos' main branch, sets up a custom `.chezmoiignore` file filtering out non-theme related files, and pushes all the files from the `.config` folder to a separate `theme` branch
- Once that's done, [another action](https://cpina.github.io/push-to-another-repository-docs/index.html) takes the files from this branch and pushes them onto an entirely different, public `pretty-dotfiles` repo, where they can be properly looked at and easily cloned by people who want to use the theme.
- In a perfect world, this process would additionally allow for a `README.md` in the target repo, as well as a screenshot folder, that wouldn't be touched by the workflow.

Again, in my head this doesn't sound hard to achieve, but I've been reading the GitHub Workflow documentation for a while now without getting anywhere. If anyone would have some helpful input, I'd greatly appreciate it!

**Comment by bytebone** [comment, marked as answer]
I've played around with this a bit more and managed to come up with a fully working solution, checking all the boxes. Should anyone come across this, admittedly edgecase, scenario, I'll publish my solution here: 

The workflow file, placed in `.github/workflows/` on your chezmoi repo, looks like this:

```yml
name: Publish theme to public repo
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: 'repo'

      - name: Build dotfiles
        run: sh repo/.build/build.sh
      
      - name: Push to public repo
        uses: cpina/github-action-push-to-another-repository@v1.6
        env: 
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with: 
          source-directory: 'output'
          destination-github-username: 'justrainer' # replace this with your github username
          destination-repository-name: 'pretty_dotfiles' # replace this with your target repo name
          commit-message: 'Updated from private repo'
          target-directory: 'dotfiles'
``` 
It requires the setup from the "Push to another repo" documentation, as this requires SSH keys. The docs can be found [here](https://cpina.github.io/push-to-another-repository-docs/setup-using-ssh-deploy-keys.html#setup-ssh-deploy-keys).

The build script being run by the GitHub action should be placed in the folder `.build` in the root of the chezmoi repo and called`build.sh`, as well as a `.chezmoiignore` file. The latter just contains your regular ignore directions as to which files should be pushed to your public repo. The build script looks like this:

```sh
#! /bin/bash

echo "Current work directory: $(pwd)"

echo "Installing chezmoi"
sh -c "$(curl -fsLS get.chezmoi.io)"

echo "Applying custom chezmoiignore"
cat repo/.build/.chezmoiignore > repo/.chezmoiignore

echo "Building dotfiles"
echo "----"
echo "BUILDING:"
./bin/chezmoi -S repo/ managed
echo "IGNORING:"
./bin/chezmoi -S repo/ ignored
echo "----"

mkdir -p output/.config
./bin/chezmoi -S repo/ -D output/ -k --force apply

echo "Done."
```
Pushing these three files to your main online repo is all you need to do (other than creating your public repo of course). On every push to the private repo, your desired files will be pushed to your public repo into the `dotfiles` subdirectory. This allows you to have a README, LICENSE and image subdirectory to theme your public repo as you wish. 

I somewhat doubt anyone will come across this or even find it useful. But in the rare case that someone found it helpful or interesting, I thought I'd share the solution.
