### DISCUSSION TITLE
Managing multiple configuration profiles

### DISCUSSION THREAD

**Discussion by AdriandMartin** [twpayne/chezmoi#2976] [Q&A] [answered]
I've been considering several alternatives to manage my dotfiles, and chezmoi seems to be the most stable and efficient. However, I've seen that dotdrop supports multiple configuration profiles, does chezmoi have a similar feature?

Thank you

**Comment by twpayne** [comment]
What exactly do you mean by a configuration profile? chezmoi supports infinite configuration profiles though configuration variables in its configuration file.

**Reply by AdriandMartin** [reply]
I was referring to a way to specify different configuration targets so that you can choose which of them to apply at the moment of restoring your dotfiles on a new machine (thanks to @halostatue for explaining it in detail in his comment). It's something like tagging a set of dotfiles that fit with a specific purpose (e.g., configuring your home workstation)

**Comment by halostatue** [comment, marked as answer]
chezmoi does not have the concept of "configuration profile" the way that [dotdrop](https://github.com/deadc0de6/dotdrop) does, but it can make similar choices through the use of configuration variables and/or machine state (such as the OS name or even the presence of certain files).

dotdrop configuration is highly manual and indirect and requires specifying a managed dotfile at least twice (once for the initial "reference" definition, and once for each configuration profile to specify which references to use). I’ve only skimmed the README, but this should show what is required:

```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
profiles:
  home:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - d_polybar
  office:
    dotfiles:
    - f_xinitrc
    - d_polybar
```

You have to define the `src/dst` references in `dotfiles` with names. It appears that there is a naming convention of `f_` for files and `d_` for directories. Then for each profile (in the example above, there are two: `office` and `home`) you have to specify each reference once where you want to apply it.

In chezmoi, you would add one configuration variable to your `~/.config/chezmoi/chezmoi.FORMAT`:

```toml
[data]
  location = "home" # or "office"
```

And then you would create a `~/.local/share/chezmoi/.chezmoiignore.tmpl` that references this like this:

```
{{ if eq "office" .location }}
.vimrc
{{ end }}
```

Now `chezmoi apply` will *correctly* apply only `~/.xinitrc` and `~/.config/polybar` when the `location` value is `"office"`.

There is light discussion of adding a configuration mapping file for v3 to make certain things easier (a number of programs which store their configuration in `~/.config/foo` on Linux store them in `~/Library/Application Support/foo/config` on macOS; this requires [templating shenanigans](https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#handle-different-file-locations-on-different-systems-with-the-same-contents) in the current version of chezmoi).

All of this to say that @twpayne is right when he says "chezmoi supports infinite configuration profiles though configuration variables in its configuration file".
