### DISCUSSION TITLE
How to handle external .env files with chezmoi

### DISCUSSION THREAD

**Discussion by mattiasbonte** [twpayne/chezmoi#3062] [Q&A] [answered]
Good evening 👋🏼 ,

I've been migrating to chezmoi these last couple of days, it's challenging but also very cool to figure everything out!
Now there is a thing i'm struggling a bit with. I have an external repository which is managed by chezmoi's `.chezmoiexternal.toml`.

This is how it's defined in .chezmoiexternal.toml:
```toml
["DEV/GO/somerepo"]
    type = "git-repo"
    url = "git@github.com:dude/soomerepo.git"
    refreshPeriod = "33h"
    ["DEV/GO/somerepo".pull]
        args = ["--ff-only"]
```

Now this repository has a `.env` file which should be created when the repository is pulled, or updated when the file was changed inside chezmoi source. I would like to be able to use chezmoi to do this for me. 

For example with a `private_DEV/GO/somerepo/dot_env.tmpl`
```
API_KEY={{ (bitwarden...) }}
```

But whenever I try to `chezmoi apply` im getting an error:
```
chezmoi: DEV/GO/somerepo: inconsistent state (/user/.local/share/chezmoi/private_DEV/GO/somerepo, git@github.com:user/somerepo.git defined in /user/.local/share/chezmoi/.chezmoiexternal.toml)
```

The question I have is, how to properly do this with chezmoi.. And is this a common pattern which is supported by chezmoi? Or am I butchering this and should tackle it in a different manner?

Thanks a lot for your time 🙏🏼 .
