### DISCUSSION TITLE
Is there any way to filter githubLatestTag?

### DISCUSSION THREAD

**Discussion by xfzv** [twpayne/chezmoi#3161] [Q&A] [answered]
I'm having the following in my `.chezmoiexternal.yml`:

```yaml
".local/bin/notesnook.AppImage":
  type: "file"
  executable: true
  url: "https://github.com/streetwriters/notesnook/releases/download/{{ (gitHubLatestRelease "streetwriters/notesnook").TagName }}/notesnook_linux_x86_64.AppImage"
  refreshPeriod: "168h"
```

It works fine for the most part, but fails sometimes. Indeed, this repository ([streetwriters/notesnook](https://github.com/streetwriters/notesnook/)) is a bit special since it provides both desktop and Android variants of the app mixed in the releases section.

As a result, if the latest tag is for an Android version like right now:

![image](https://github.com/twpayne/chezmoi/assets/78810647/eb979cf6-b6b3-48d0-8d31-03f732bea492)

`chezmoi apply` will fail as expected with the following error:

```console
❯ chezmoi apply
chezmoi: .local/bin/notesnook.AppImage: https://github.com/streetwriters/notesnook/releases/download/2.6.1-android/notesnook_linux_x86_64.AppImage: 404 Not Found
```

Is there a way to filter the template in order to use the latest tag that doesn't contain `-android` for example?

With:

```yaml
url: "https://github.com/streetwriters/notesnook/releases/download/{{ (gitHubLatestRelease "streetwriters/notesnook").TagName | replaceAllRegex "-android" "" }}/notesnook_linux_x86_64.AppImage"
```

I can get `chezmoi` to fetch `https://github.com/streetwriters/notesnook/releases/download/2.6.1/notesnook_linux_x86_64.AppImage` so `-android` is removed from the URL correctly, but of course it still fails because there's no 2.6.1 for desktop.

Any idea is appreciated.
