### DISCUSSION TITLE
Question regarding a `run_after` script modifying an external file

### DISCUSSION THREAD

**Discussion by xfzv** [twpayne/chezmoi#3255] [Q&A] [answered]
I'm using the following in my `.chezmoiexternal.yml` file:

```yaml
{{ $FMBurl := "https://github.com/datguypiko/Firefox-Mod-Blur/archive/refs/heads/master.zip" }}
".mozilla/firefox/default-release/chrome/Firefox-Mod-Blur":
  type: "archive"
  url: "{{ $FMBurl }}"
  refreshPeriod: "168h"
  stripComponents: 1
  include: [ "*/image/**",
             "*/userChrome.css",
             "*/userContent.css"]
```

I need to change a value in `userChrome.css` so I'm using the following `.chezmoiscripts/run_after_01_firefox_mod_blur_fix_space.sh` script to do so:

```bash
#!/usr/bin/env bash

file="$HOME/.mozilla/firefox/default-release/chrome/Firefox-Mod-Blur/userChrome.css"

sed -i "s/--firefoxcss-control-buttons-margin: 95px;/--firefoxcss-control-buttons-margin: 0px;/g" "$file"
```

When I run `chezmoi apply`, I'm always getting the following message:

```console
.mozilla/firefox/default-release/chrome/Firefox-Mod-Blur/userChrome.css has changed since chezmoi last wrote it? diff/overwrite/all-overwrite/skip/quit
```

```diff
 221⋮ 221│:root {
 222⋮ 222│  --firefoxcss-top-bar-border-bottom-size: 1px;
 223⋮ 223│  --firefoxcss-border-radius: 10px;
- 224⋮    │  --firefoxcss-control-buttons-margin: 0px;
+    ⋮ 224│  --firefoxcss-control-buttons-margin: 95px;
 225⋮ 225│  --firefoxcss-tab-min-width: 110px;
 226⋮ 226│  --firefoxcss-tab-max-width: 150px;
 227⋮ 227│}
```

If I understand the [Application order](https://www.chezmoi.io/reference/application-order/) doc page correctly, this is expected. The `run_after` script is run last (step 6). So when running `chezmoi apply`, `chezmoi` detects the change at step 5 when applying the external `userChrome.css` containing the original content and prompts the user what should be done.

This makes sense, but is there a way to avoid that prompt and automatically apply the changes from the `run_after` script?

**Comment by halostatue** [comment]
I was thinking about something related to this today, and think that at least some of the package management scripts that I have could be superseded by externals *if* I were able to:

- run a command to get the external:

  ```yaml
  go/bin/age:
    command: "go install filippo.io/age/cmd/...@latest"
    refreshPeriod: 168h
  ```

- run a command *after* getting the external

  ```yaml
  go/src/age:
    type: git-repo
    refreshPeriod: 168h
    pull: { args: ['--ff-only'] }
    url: https://github.com/filosottile/age
    command: 'go install ./cmd/...'
  ```

I only have `refreshPeriod` in my externals right now, so I can’t say whether this would solve your problem, but it is worth considering.

**Reply by bradenhilton** [reply]
https://github.com/twpayne/chezmoi/issues/2211 has a similar discussion.

**Reply by xfzv** [reply]
This `command` string looks appealing at first sight, but wouldn't the scripts generally still be more flexible/powerful?

_generally_, because in this case it looks like I could have used my `sed` command directly in `.chezmoiexternal.yml` instead of relying on an extra `userChrome.css` file out of the source directory (thanks again to @bradenhilton for the help on this).

I'm obviously far less technical than both of you so this is just my general impression.

**Comment by bradenhilton** [comment]
chezmoi doesn't know that `userChrome.css` is being modified by itself (via a script), so it thinks the file was modified externally, hence the message.

Achieving this without the prompt would likely require allowing `modify_` scripts to work on externals, with the limitation that they can only be run after the target state is updated.

At the moment, you could consider moving the external somewhere else (e.g. `.config/firefox/mods`) and converting your `run_after_` script into a basic custom `modify_` script by writing the file to its final destination (which itself is not managed by chezmoi) after substituting values. You could combine this with the `onchange_` attribute and include a hash of the file in `.config/firefox/mods` so that the script only runs when the external changes, as described in https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/#run-a-script-when-the-contents-of-another-file-changes.

**Comment by xfzv** [comment, marked as answer]
> At the moment, you could consider moving the external somewhere else (e.g. `.config/firefox/mods`) 

Do you mean saving it to another location, like this?

```yaml
# .chezmoiexternal.yml

{{ $FMBurl := "https://github.com/datguypiko/Firefox-Mod-Blur/archive/refs/heads/master.zip" }}

".mozilla/firefox/default-release/mods/Firefox-Mod-Blur":
  type: "archive"
  url: "{{ $FMBurl }}"
  refreshPeriod: "168h"
  stripComponents: 1
  include: [ "*/userChrome.css" ]
```

> and converting your `run_after_` script into a basic custom `modify_` script by writing the file to its final destination (which itself is not managed by chezmoi) after substituting values.

I don't really understand the [instructions](https://www.chezmoi.io/user-guide/manage-different-types-of-file/#manage-part-but-not-all-of-a-file) regarding this.

I tried:

```css
/* ~/dotfiles/dot_mozilla/firefox/default-release/chrome/Firefox-Mod-Blur/modify_userChrome.css */

{{- /* chezmoi:modify-template */ -}}
{{- .chezmoi.stdin | replace
"--firefoxcss-control-buttons-margin: 95px"
"--firefoxcss-control-buttons-margin: 0px"
-}}
```

but of course it doesn't work. How am I supposed to perform the string substitution in `~/.mozilla/firefox/default-release/mods/Firefox-Mod-Blur/userChrome.css` and then write the final file to `~/.mozilla/firefox/default-release/chrome/Firefox-Mod-Blur/userChrome.css`?

**Reply by bradenhilton** [reply]
Apologies if I was not clear enough.

In my comment I wasn't referring to a `modify_` template, as there is no way to run this after the target state is updated, which would mean the replacement is always one `chezmoi apply` behind.

Rather, I was referring to creating a `run_onchange_after_` script in which you read the **external** `userChrome.css` manually, perform the replacement, then write that to the proper `userChrome.css` path. Perhaps something like this:

```sh
#!/usr/bin/env bash

{{ $source := joinPath .chezmoi.homeDir ".mozilla/firefox/default-release/mods/Firefox-Mod-Blur/userChrome.css" -}}
{{ $target := joinPath .chezmoi.homeDir ".mozilla/firefox/default-release/chrome/Firefox-Mod-Blur/userChrome.css" -}}

{{ if stat $source }}
# userChrome.css hash: {{ include $source | sha256sum }}

sed "s/--firefoxcss-control-buttons-margin: 95px;/--firefoxcss-control-buttons-margin: 0px;/g" {{ $source | quote }} > {{ $target | quote }}
{{ end }}
```

(untested)

**Reply by xfzv** [reply]
Appreciate the further explanation, I completely missed the point initially...

Your attempt works just fine on my end along with:

```yaml
# .chezmoiexternal.yml

{{ $FMBurl := "https://github.com/datguypiko/Firefox-Mod-Blur/archive/refs/heads/master.zip" }}

".mozilla/firefox/default-release/mods/Firefox-Mod-Blur":
  type: "archive"
  url: "{{ $FMBurl }}"
  refreshPeriod: "168h"
  stripComponents: 1
  include: [ "*/userChrome.css" ]
```

Thank you!
