### DISCUSSION TITLE
Issue w/ Folder Diff

### DISCUSSION THREAD

**Discussion by ProfessorManhattan** [twpayne/chezmoi#3448] [Q&A]
I'm unable to run `chezmoi` without the `-k` flag because I have my diff set up with the following:

```
diff:
  command: delta
  pager: delta
  format: git
  args:
    - "--paging"
    - never
  exclude:
    - externals
    - scripts
```

It fails when the diff is used comparing a folder to `/dev/null`. Is there anyway I can add all directories to the `exclude`? Or is there an easier way of addressing this issue?

**Comment by twpayne** [comment]
You can add `dirs` to the list of types to exclude:

```yaml
diff:
  exclude:
  - externals
  - scripts
  - dirs
```
