### DISCUSSION TITLE
Is there a way to output some messages in between `.chezmoiexternal` packages installation/updates?

### DISCUSSION THREAD

**Discussion by owpac** [twpayne/chezmoi#3654] [Ideas]
Hello,

I have this really basic `.chezmoiexternal.yaml.tmpl` file:

```yaml
".oh-my-zsh":
  type: "git-repo"
  url: "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod: "168h"

".oh-my-zsh/custom/themes/powerlevel10k":
  type: "git-repo"
  url: "https://github.com/romkatv/powerlevel10k.git"
  refreshPeriod: "168h"

".oh-my-zsh/custom/plugins/zsh-syntax-highlighting":
  type: "git-repo"
  url: "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod: "168h"

".oh-my-zsh/custom/plugins/zsh-autosuggestions":
  type: "git-repo"
  url: "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod: "168h"

".oh-my-zsh/custom/plugins/autoupdate":
  type: "git-repo"
  url: "https://github.com/TamCore/autoupdate-oh-my-zsh-plugins"
  refreshPeriod: "168h"
```

I think there is a basic need to have some kind of delimiters when `chezmoi` is cloning or pulling those different packages. So I'm just trying to print some kind of message in between each package. Is this possible? Is this a new feature?

Thanks a lot.

**Comment by twpayne** [comment]
chezmoi has had a `--progress` flag that shows the progress of downloads since #2369. Is this sufficient?

**Reply by owpac** [reply]
I missed this parameter, but I'm not sure that it's the right solution for the need 🤔 

What I was thinking, in my case, was something like this for `.chezmoiexternal.yaml.tmpl`:
```yaml
".oh-my-zsh":
  type: "git-repo"
  url: "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod: "168h"
  message: "Installing Oh My ZSH..."
```

And when `chezmoi apply` is executing, there is no message from `git` command, everything is muted (`git clone`, `git pull`, etc.).

Because in the case of `type: "git-repo"`, there are couples of states possible (cloning, pulling or 'up to date') which are quite verbose but not needed in the context of chezmoi. Moreover, if you have multiple `type: "git-repo"`, it's all packed up together and not really readable during any of those states.

Note: I couldn't make `--progress` worked 🤔 

```console
$ chezmoi apply --refresh-externals --progress on
Already up to date.
Already up to date.
Already up to date.
Already up to date.
Already up to date.
```
