### DISCUSSION TITLE
How do you manage machine-to-machine differences when you have lots of different hosts?

### DISCUSSION THREAD

**Discussion by shawly** [twpayne/chezmoi#3773] [General]
I've been using chezmoi for a while now, expanding my dotfiles for all of my Linux hosts up until a few days ago. Recently I started adding my Windows dotfiles aswell and my dotfiles repo is really starting to become cluttered now and I'm kind of losing sight of what stuff gets added to which host.

I began using `.chezmoidata` to set some distro specific defaults for hosts and added a per-hostname config for very host specific settings. It now looks like this:

```shell
~/.local/share/chezmoi:
├── .chezmoitemplates/
│   └── machine.yaml.tmpl
├── linux/
│   ├── .chezmoidata/
│   │   ├── arch_alpine.yaml
│   │   ├── arch_debian.yaml
│   │   ├── arch_manjaro.yaml
│   │   ├── arch_ubuntu.yaml
│   │   ├── host_alpha.yaml
│   │   ├── host_beta.yaml
│   │   └── host_gamma.yaml
│   ├── .chezmoitemplates  -> ../.chezmoitemplates/    # symlink
│   └── ...   # dotfiles for linux hosts
├── windows/
│   ├── .chezmoidata/
│   │   ├── arch_windows.yaml
│   │   ├── host_omega.yaml
│   ├── .chezmoitemplates  -> ../.chezmoitemplates/    # symlink
│   └── ...   # dotfiles for windows hosts
├── .chezmoiroot    # set to windows or linux manually for my hosts
└── .gitignore
```

The `arch_*.yaml` files contain distro specific variables, like which packages shall be installed by default, the package manager used and which tools like nvm, oh-my-zsh, sdkman etc. need certain prerequisite packages installed, like this:

```yaml filename="arch_ubuntu.yaml"
# yaml-language-server: $schema=../../.schema/chezmoi-machine.schema.json
---
machine:
  arch:
    ubuntu:
      package_manager:
        apt-get:
          args: '-y install'
          sudo: true
          packages:
            byobu: true
            tmux: true
            vim: true
      tools:
        p10k:
          fg_color: 202
        omz:
          package_manager:
            apt-get:
              packages:
                autojump: true
                git: true
                zsh: true
        nvm:
          package_manager:
            apt-get:
              packages:
                git: true
        sdkman:
          package_manager:
            apt-get:
              packages:
                zip: true
                unzip: true
        qemu:
          package_manager:
            apt-get:
              packages:
                dnsmasq: true
                bridge-utils: true
                dmidecode: true
                libguestfs0: true
                qemu-kvm: true
                virtinst: true
                libvirt-clients: true
                libvirt-daemon-system: true
```

And the `host_*.yaml` files contain host specific configurations:

```yaml
# yaml-language-server: $schema=../../.schema/chezmoi-machine.schema.json
---
machine:
  host:
    alpha:
      headless: true
      profile: private
      type: server
      ssh_config:
        - |
          Host backups
            HostName "my-backup-space.com"
            User username-alpha
            Port 23
      tools:
        p10k:
          install: true
        qemu:
          install: true
```

And the `machine.yaml.tmpl` merges all this information for the current host like this:

```go
---
{{ $archData := get .machine.arch "default" }}
{{ $hostData := get .machine.host "default" }}

{{- if eq .chezmoi.os "linux" -}}
{{-   if (hasKey .machine.arch .chezmoi.osRelease.id) -}}
{{-     $archData := mergeOverwrite $archData (get .machine.arch .chezmoi.osRelease.id) -}}
{{-   end -}}
{{- else if eq .chezmoi.os "windows" -}}
{{-   $archData := mergeOverwrite $archData (get .machine.arch .chezmoi.os) -}}
{{- end -}}

{{- if (hasKey .machine.host .chezmoi.hostname) -}}
{{-     $hostData := mergeOverwrite $hostData (get .machine.host .chezmoi.hostname) -}}
{{- end -}}

{{- $machineData := mergeOverwrite $archData $hostData -}}
{{ toYaml $machineData }}
```

Which can be included in a dotfile template with a single line in the header of a file:

```go
{{- $machine := (fromYaml (includeTemplate "machine.yaml.tmpl" .)) -}}
```

This allows me to query machine specific data to ignore specific files via .chezmoiignore and only apply certain configs to specific types of hosts, like this for the .chezmoiignore:

```go
# include p10k config
{{- if $machine.tools.p10k.install }}
!.p10k.zsh
{{ end }}

# add ssh-agent.service for non server machines
{{- if ne $machine.type "server" }}
!.config/systemd/user/
.config/systemd/user/*
!.config/systemd/user/ssh-agent.service
{{- end }}
```

Or I can enable p10k in my .zshrc:
```go
{{ if $machine.tools.p10k.install }}
ZSH_THEME="powerlevel10k/powerlevel10k" 
{{ else }}
ZSH_THEME="agnoster"
{{ end }}
```
Where the $machine.tools.p10k.fg_color is set to orange for Ubuntu so the zsh on my Ubuntu servers is orange, while Manjaro uses the default green theme and EndeavourOS is violet.

To install the packages I use a script that leverages this setup:

```bash
#!/usr/bin/env bash

set -e

echo "[run_onchange_before_000_install-packages.sh] Start"

{{ $machine := (fromYaml (includeTemplate "machine.yaml.tmpl" .)) -}}

{{ range $package_manager, $options := $machine.package_manager }}
{{-     $packages := $options.packages -}}
{{-     $command := $package_manager -}}
{{-     $args := $options.args -}}
{{-     $sudo := $options.sudo }}

{{-     range $key, $tool := $machine.tools -}}
{{-         if (and $tool.install (hasKey $tool "package_manager") (hasKey $tool.package_manager $package_manager)) -}}
{{-             $tool_package_manager := get $tool.package_manager $package_manager -}}
{{-             if (and (hasKey $tool_package_manager "packages") ($tool_package_manager.packages)) -}}
{{-                 $packages := merge $packages $tool_package_manager.packages -}}
{{-             end -}}
{{-         end -}}
{{-     end -}}

# hash: {{ cat $packages | sha256sum }}
packages=(
{{-     range $package, $install := $packages -}}
{{-         if $install -}}
{{-             print $package " " -}}
{{-         end -}}
{{-     end -}}
)

if command -v {{ $command }} &>/dev/null; then
    echo "Installing packages via {{ $command }}: ${packages[@]}..."
    {{ if $sudo }}sudo {{ end }}{{ $command }} {{ $args }} "${packages[@]}" || exitCode="$?"
    if [[ "${exitCode:-0}" -ne 0 ]]; then
        echo "Failed to install packages, aborting!"
        exit "${exitCode}"
    fi
else
    echo "Package manager {{ $command }} not found, skipping package installation!"
fi

{{ end }}

echo "[run_onchange_before_000_install-packages.sh] End"
```

With this setup I can set up a new host, add a yaml for it to my .chezmoidata configs and initialize the host with my dotfiles via chezmoi init easily. But I am not yet sure if stuff like installing packages etc. should be done through chezmoi. I'd rather use Ansible for managing the host itself. While I am satisfied with this setup, I think it is not perfect and I need some inspiration on how I could improve this.

How do you manage lots of machines? Are you only using templates or do you have a more generic approach?
