### DISCUSSION TITLE
externals: how to get nightly builds updates?

### DISCUSSION THREAD

**Discussion by xfzv** [twpayne/chezmoi#3897] [Q&A] [answered]
I'm using the following in my `.chezmoiexternals` directory and it works just fine:

```yaml
".local/bin/":
  type: "archive"
  url: "https://github.com/sxyazi/yazi/releases/download/nightly/yazi-x86_64-unknown-linux-gnu.zip"
  refreshPeriod: "168h"
  stripComponents: 1
  include: ["*/ya", "*/yazi"]
```

However, even when refreshing externals with

```console
% chezmoi apply -R
```

`chezmoi` doesn't grab the latest archive and my binaries (`~/.local/bin/ya` and `~/.local/bin/yazi`) are not updated.

I guess this is because there is no version detection mechanism unlike i.e.

```yaml
  url: "https://github.com/sxyazi/yazi/releases/download/{{ (gitHubLatestRelease "sxyazi/yazi").TagName }}/yazi-x86_64-unknown-linux-gnu.zip"
```

so `chezmoi` always thinks I already have the latest version.

Is there a way to get updates in this scenario with nightly builds?

Thanks!
