### DISCUSSION TITLE
`chezmoi doctor` - `.chezmoiexternals/chezmoi.toml.tmpl` detected as "suspicious-entries"

### DISCUSSION THREAD

**Discussion by xfzv** [twpayne/chezmoi#3966] [Q&A] [answered]
I'm managing `chezmoi` binary as an external with `~/dotfiles/.chezmoiexternals/chezmoi.toml.tmpl`:

```toml
{{ if eq .distro "gentoo" }}
[".local/bin/chezmoi"]
type = "file"
executable = true
url = "https://github.com/twpayne/chezmoi/releases/download/{{ (gitHubLatestRelease "twpayne/chezmoi").TagName }}/chezmoi-linux-amd64"
refreshPeriod = "168h"
{{ end }}
```

which works just fine. However, I noticed that `chezmoi doctor` prints the following warning:

```console
% chezmoi doctor
RESULT    CHECK                       MESSAGE
[...]
ok        source-dir                  ~/dotfiles is a git working tree (clean)
warning   suspicious-entries          ~/dotfiles/.chezmoiexternals/chezmoi.toml.tmpl
[...]
```

I guess the warning is because the filename contains `chezmoi`, considering it disappears if I rename `chezmoi.toml.tmpl` to something else, e.g. `binary.toml.tmpl`.

Just curious if this could be improved.
