### DISCUSSION TITLE
Can't find how to use external files

### DISCUSSION THREAD

**Discussion by LeGmask** [twpayne/chezmoi#3977] [Q&A] [answered]
```toml
[".config/k9s/skins"]
type = "archive"
url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
exact = false
strip_components = 2
refreshPeriod = "168h"
include = ["dist/*.yaml"]
```

I've tried to add an external module, but can't find how to make this work, either I have the full archive or an empty folder.
