### DISCUSSION TITLE
Integrating external sources into git repo rather than at runtime?

### DISCUSSION THREAD

**Discussion by stonewalljones** [twpayne/chezmoi#4165] [Q&A]
I'd like to be able to use chezmoi to incorporate single files from eternal git repos (i.e. https://github.com/grml/grml-etc-core/blob/master/etc/zsh/zshrc and https://github.com/gpakosz/.tmux/blob/master/.tmux.conf). I'd like these files fully in the repo so the current .chezmoiexternal functionality doesn't looks like it fits my need and since I want to just pull the single files it doesn't look like git submodules would work either. 

Is what I've described possible with chezmoi currently?

**Comment by twpayne** [comment]
Yes, you can use externals with GitHub's "raw" URLs, for example:

```toml
[".zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/grml/grml-etc-core/refs/heads/master/etc/zsh/zshrc"
    refreshPeriod = "168h"
```
