### DISCUSSION TITLE
How can I execute a template-based script before running `chezmoi apply`?

### DISCUSSION THREAD

**Discussion by jbwfu** [twpayne/chezmoi#4221] [Q&A] [answered]
My `.chezmoiexternal.yaml.tmpl` file uses a YAML file located at `.chezmoi.cacheDir`, which is generated by a script that records the installation status of programs. However, the script itself is dynamically generated based on a template. What would be the best way to handle this?

Currently, my approach is as follows:

### my `.chezmoi.yaml.tmpl`:

```yaml
{{/* Write a script to check the installation status of programs. */}}
{{- $filepath := joinPath .chezmoi.cacheDir "checkinstalled.sh" -}}
{{- output "sh" "-c" (list "mkdir" "-p" .chezmoi.cacheDir | join " ") -}}
{{- $context := output "sh" "-c" (list "chezmoi" "execute-template" "'{{" "includeTemplate" "\"scripts/checkinstalled.sh.tmpl\"" "." "}}'" ">" $filepath | join " ") -}}

hooks:
  apply:
    pre:
      command: "sh"
      args: [{{- $filepath | quote -}}]
```

### my `.chezmoitemplates/scripts/checkinstalled.sh.tmpl`:

```sh
#!/usr/bin/env sh

programs= {{- .programs.needcheck | join " " | quote }}

mkdir -p {{ .chezmoi.cacheDir | quote }}

for program in $programs; do
  installed=true
  command -v "$program" > /dev/null 2>&1 || installed=false

  printf "%s:\n  installed: %s\n" "$program" "$installed"
done > {{ joinPath .chezmoi.cacheDir "installstatus.yaml" }}
```

**Comment by bradenhilton** [comment]
Have you tried a [`run_before_`](https://www.chezmoi.io/reference/target-types/#scripts) script?

**Reply by jbwfu** [reply]
According to the content in the [Application order](https://www.chezmoi.io/reference/application-order/), `run_before_` is supposed to be executed after reading `.chezmoiexternal.yaml.tmpl`.

 My actual testing also confirms this: without adding any hooks, an error occurs and the process exits because the corresponding YAML file cannot be found before the `run_before_` script is executed.

**Reply by bradenhilton** [reply]
What are you trying to achieve with this? It's not immediately clear based on your post and it's possible there is a better way to do it.

What are the contents of your `.chezmoiexternal.yaml.tmpl`?

**Reply by jbwfu** [reply]
## `.chezmoiexternal.yaml.tmpl`:
```
{{- $data := fromYaml (include (joinPath .chezmoi.cacheDir "programs.yaml")) -}}
{{- if ne .chezmoi.os "windows" -}}

{{- if $data.programs.zsh.installed -}}
.config/shell/oh-my-zsh:
  type: git-repo
  url: https://github.com/ohmyzsh/ohmyzsh.git
  refreshPeriod: 168h
{{- end }}

{{- if $data.programs.tmux.installed }}
.config/tmux/oh-my-tmux:
  type: git-repo
  url: https://github.com/gpakosz/.tmux.git
  refreshPeriod: 168h
{{- end -}}

{{- end -}}
```

I use the generated `programs.yaml` file to track the installation status of programs and decide whether to fetch the corresponding remote content based on that installation status. My current configuration achieves this goal, but it is somewhat complicated, and I would like a simpler way to do it.

**Reply by bradenhilton** [reply, marked as answer]
Could you not replace your script with [`lookPath`](https://www.chezmoi.io/reference/templates/functions/lookPath/)s in your external template? e.g.

```text
{{- if lookPath "zsh" -}}
.config/shell/oh-my-zsh:
  type: git-repo
  url: https://github.com/ohmyzsh/ohmyzsh.git
  refreshPeriod: 168h
{{- end }}
```

For what it's worth, I prefer to build my configs with `dict`s/`list`s etc., then finally output them with `to{Yaml,Toml,PrettyJson}`. For example, here are my externals for `mpv`:

```text
{{- $externals := dict -}}

{{- with $repo := "CogentRedTester/mpv-sub-select" -}}
{{-   $_ := set $externals "scripts/sub-select.lua" (dict
        "type" "file"
        "url" (printf "https://github.com/%s/raw/master/sub-select.lua" $repo)
        "refreshPeriod" "168h")
-}}
{{- end -}}

{{- with $owner := "po5" -}}
{{-   range $repo := (list "chapterskip" "thumbfast") -}}
{{-     $_ := set $externals (printf "scripts/%s.lua" $repo ) (dict
          "type" "file"
          "url" (printf "https://github.com/%[1]s/%[2]s/raw/master/%[2]s.lua" $owner $repo)
          "refreshPeriod" "168h")
-}}
{{-   end -}}
{{- end -}}

{{- with $repo := "tomasklaen/uosc" -}}
{{-   with $version := (gitHubLatestRelease $repo).GetTagName -}}
{{-     $_ := set $externals "fonts" (dict
          "type" "archive"
          "url" (printf "https://github.com/%s/releases/download/%s/uosc.zip" $repo $version)
          "stripComponents" 1
          "include" (list "fonts/**"))
-}}
{{-     $_ := set $externals "scripts" (dict
          "type" "archive"
          "url" (printf "https://github.com/%s/releases/download/%s/uosc.zip" $repo $version)
          "stripComponents" 1
          "include" (list "scripts/**")
          "exclude" (list 
            "fonts/**"
            "scripts/uosc/char-conv/**"))
-}}
{{-   end -}}
{{- end -}}

{{- $externals | toToml -}}
```

And here is the result of the template:

```toml
[fonts]
include = ['fonts/**']
stripComponents = 1
type = 'archive'
url = 'https://github.com/tomasklaen/uosc/releases/download/5.7.0/uosc.zip'

[scripts]
exclude = ['fonts/**', 'scripts/uosc/char-conv/**']
include = ['scripts/**']
stripComponents = 1
type = 'archive'
url = 'https://github.com/tomasklaen/uosc/releases/download/5.7.0/uosc.zip'

['scripts/chapterskip.lua']
refreshPeriod = '168h'
type = 'file'
url = 'https://github.com/po5/chapterskip/raw/master/chapterskip.lua'

['scripts/sub-select.lua']
refreshPeriod = '168h'
type = 'file'
url = 'https://github.com/CogentRedTester/mpv-sub-select/raw/master/sub-select.lua'

['scripts/thumbfast.lua']
refreshPeriod = '168h'
type = 'file'
url = 'https://github.com/po5/thumbfast/raw/master/thumbfast.lua'
```
