### DISCUSSION TITLE
How to escape '{{}}' in a templated chezmoi config file

### DISCUSSION THREAD

**Discussion by Nova38** [twpayne/chezmoi#4249] [Q&A] [answered]
my chezmoi.toml file is a template and I want to use vscode as the editor. To do that i use the following snippit. However chezmoi tries to fill in the template when the config is populated during `chezmoi init` and errors out. Is there a way to escape '{{x}}' in a templated config file? 

```toml
[merge]
    tool = "vscode"
    # [mergetool "vscode"]
    # cmd = code --wait $MERGED
    command = "code"
    args = ["-m", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
```
