### DISCUSSION TITLE
`chezmoi doctor` marks `.config/chezmoi/chezmoi.toml` as suspicious.

### DISCUSSION THREAD

**Discussion by jmigual** [twpayne/chezmoi#4282] [Q&A] [answered]
In my dotfiles repo (https://github.com/jmigual/dotfiles) I have a very basic `chezmoi.toml`:

```toml
[diff]
    exclude = ["scripts"]
```

And it is marked as suspicious. I don't know why.
