### DISCUSSION TITLE
promptChoice / promptChoiceOnce disregarding overlapping results

### DISCUSSION THREAD

**Discussion by Lockszmith-GH** [twpayne/chezmoi#4428] [Q&A]
With the following `chezmoi.toml.tmpl`:

```toml
# configuration
{{- $options := list "locked-full" "locked" "normal" }}
{{- $selected := promptChoice "Make a choice" $options "locked-full" }}

[data]
  options = {{- $selected | quote }}
```

```
#  👻 content is displayed in grey (ghosted)
chezmoi init --apply --prompt && cz data | jq -c '.chezmoi.config.data.style'
Zellij default style? 👻locked-full/locked/normal, default locked-full

# result when hitting <enter>
{"options":"locked-full"}

# result when typing `locked` (appreas right after I hit `d`)
{"options":"locked"}
```

### Problem Description
Only accepting default allows selecting locked-full, otherwise, only locked or normal are selectable.

Possible solutions: wait for <Enter> to confirm entry, this will allow entering options after the last letter.
Another possible solution, allow up/down + enter navigation between options.
