### DISCUSSION TITLE
ignored folder containing external git repo not entirely ignored - bug or feature?

### DISCUSSION THREAD

**Discussion by j-lakeman** [twpayne/chezmoi#4443] [Q&A] [answered]
**Setup:**

`chezmoiignore`:
```
{{- if .headless }}
.config/alacritty
{{- end }}
```

`.chezmoiexternal.toml`:
```toml
[".config/alacritty/themes"]
type          = "git-repo"
url           = "https://github.com/alacritty/alacritty-theme"
refreshPeriod = "168h"
clone.args    = ["--depth", "1"]
```

**expected behaviour:**

ignore entire `.config/alacritty` folder corresponding to `.chezmoiignore`

**actual behaviour on headless machine::**
```console
DA .config/alacritty
DA .config/alacritty/themes
```

I'm not sure whether this is a bug or feature. Pls help to resolve this. Awesome application btw, THX a lot!
