### DISCUSSION TITLE
Use webproxy with kerberos for external tools

### DISCUSSION THREAD

**Discussion by papanito** [twpayne/chezmoi#4450] [Q&A] [answered]
I sit behind a webproxy with kerberos authentication. Can, and if yes, how do I configure chezmoi to use kerberos or alternatively username and password to authenticate against the webproxy

`.chezmoiexternal.toml` contains

```toml
[ ".local/share/externals/atuin/" ]
    type = "archive"
    url = "https://github.com/atuinsh/atuin/releases/download/v18.6.1/atuin-x86_64-unknown-linux-musl.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    executable = true
```

However `chezmoi apply` fails with 

```
chezmoi: Get "https://github.com/atuinsh/atuin/releases/download/v18.6.1/atuin-x86_64-unknown-linux-musl.tar.gz": authenticationrequired
```
