### DISCUSSION TITLE
Pin external to specific commit?

### DISCUSSION THREAD

**Discussion by xfzv** [twpayne/chezmoi#4478] [Q&A] [answered]
I have a bunch of files managed as externals such as:

```toml
[".config/yazi/plugins/augment-command.yazi/main.lua"]
type = "file"
url = "https://raw.githubusercontent.com/hankertrix/augment-command.yazi/main/main.lua"
refreshPeriod = "72h"
```

Sometimes, I'd like to pin some of them to a specific commit.

I read [include-files-from-elsewhere](https://www.chezmoi.io/user-guide/include-files-from-elsewhere) but it doesn't seem to be supported.

Is there actually a way to do this?

**Comment by twpayne** [comment, marked as answer]
Yes, use the commit in the URL, for example:

```toml
[".config/yazi/plugins/augment-command.yazi/main.lua"]
type = "file"
url = "https://raw.githubusercontent.com/hankertrix/augment-command.yazi/9b15ea44b8934543b97e08d61e2ffa2d3c66ff29/main.lua"
```

Notice that you don't need to set `refreshPeriod` as the contents of the URL should never change.
