### ISSUE TITLE
Taskfile integration when using templates

### ISSUE THREAD

**Issue by onedr0p** [twpayne/chezmoi#1129]
## Is your feature request related to a problem? Please describe.

Hi 👋 I would like to integrate [Taskfile](https://github.com/go-task/task) with chezmoi. Taskfile also uses gotmpl so there is a conflict when chezmoi interpolates the variables.

Consider the following:

```yaml
# Taskfile.yml.tmpl
---
version: '3'
vars:
  CHEZMOI_LOCAL: "{{.chezmoi.sourceDir}}"
tasks:
  test:
    desc: Write out CHEZMOI_LOCAL
    cmds:
    - echo {{ .CHEZMOI_LOCAL }}
    silent: true
```

Let's see what happens on `chezmoi diff`

```
chezmoi: template: dot_taskfiles/Taskfile.yml.tmpl executing "dot_taskfiles/Taskfile.yml.tmpl " at <.CHEZMOI_LOCAL>: map has no entry for key "CHEZMOI_LOCAL"
```

## Describe the solution you'd like

I am not sure the best course of integration, but what I was thinking is that you could prefix Taskfile vars with `taskfile` and have chezmoi replace the var name and not interpolate the values.

Considering the following:

```yaml
# Taskfile.yml.tmpl
---
version: '3'
vars:
  CHEZMOI_LOCAL: "{{.chezmoi.sourceDir}}"
tasks:
  test:
    desc: Write out CHEZMOI_LOCAL
    cmds:
    - echo {{ taskfile.CHEZMOI_LOCAL }}
    silent: true
```

Chezmoi would then render this like so after the tmpl has been applied

```yaml
# Taskfile.yml
---
version: '3'
vars:
  CHEZMOI_LOCAL: "/path/to/sourceDir"
tasks:
  test:
    desc: Write out CHEZMOI_LOCAL
    cmds:
    - echo {{.CHEZMOI_LOCAL}}
    silent: true
```

Again, I really don't know the best way for chezmoi to handle this (if it could) but that seems possible?

## Describe alternatives you've considered

Not using Taskfile gotmpl vars in my taskfiles and only use chezmoi vars, but that would then reduce some functionality of Taskfile.

**Comment by twpayne** [comment]
OK, so having Go templates generate Go templates is going to get a little meta, but here are some tips that might help:

You can avoid template commands being executed by enclosing them in `{{ "..." }}`. This means that the first template pass (chezmoi) will replace the block with the contents of the string literal.

Secondly, you can use the `printf` template generate more complex template instructions if needed.

So, for your example, I think you'll want something like:

```yaml
# Taskfile.yml.tmpl
---
version: '3'
vars:
  CHEZMOI_LOCAL: {{ .chezmoi.sourceDir | quote }}
tasks:
  test:
    desc: Write out CHEZMOI_LOCAL
    cmds:
    - echo {{ "{{ taskfile.CHEZMOI_LOCAL }}" }}
    silent: true
```
