### ISSUE TITLE
User variables in `chezmoi.toml.tmpl` not available in first `init` run

### ISSUE THREAD

**Issue by davidolrik** [twpayne/chezmoi#1213]
Upon first run of `sh -c "$(curl -fsLS git.io/chezmoi)" -- init davidolrik --apply` I get the following template error:

```sh
chezmoi: template: dot_config/private_hub.tmpl:2:14: executing "dot_config/private_hub.tmpl" at <.me.github.username>: map has no entry for key "me"
```

`dot_config/private_hub.tmpl` contains this:

```yaml
github.com:
- user: {{ .me.github.username }}
  protocol: https
```

and my `chezmoi.toml.tmpl` has a section with the referenced variable:

```toml
[data.me.github]
username = "davidolrik"
```

After the first run, the contents of `chezmoi.toml` is correct, and a second run installs the `dot_config/private_hub.tmpl` as expected.

So it seems that the `chezmoi.toml` is generated correctly, but not reloaded / made available to other templates during the first `init`.
