### ISSUE TITLE
Support .zip for external archives

### ISSUE THREAD

**Issue by ArturDorochowicz** [twpayne/chezmoi#1378]
As far as I see, currently .tar.gz, .tgz, .tar.bz2, .tbz2 archives are supported as external archives. It'd be nice to have support for .zip archives as well.    

I'd like something like this to work:
```toml
[".local/share/fonts/delugia-mono-complete"]
type = "archive"
url = "https://github.com/adam7/delugia-code/releases/latest/download/delugia-mono-complete.zip"
exact = true
stripComponents = 1
```

Currently when I specify a zip archive in `.chezmoiexternal.toml` file, I get an error during `chezmoi apply` saying `unknown format`. 

I think this is the code responsible for this:
https://github.com/twpayne/chezmoi/blob/6e8757d4786d2343a5d63c1d7001491d5a3b184d/internal/chezmoi/sourcestate.go#L1489-L1499
