### ISSUE TITLE
chezmoi externals of `git` type

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1421]
## Is your feature request related to a problem? Please describe.

Not a big problem, but I'm recently in love with chezmoi's external feature, and would like to extend it even more. The concern I have about using archives instead of direct git repositories is that they would take a lot longer to update than when using just `git pull`, as git would only download the changes.

Another thing is that with `git` we don't need to know the name of branch, if the goal is to clone the default. If Oh-My-ZSH changes their default branch from master to main, then probably the current archive url using master would stop working.

## Describe the solution you'd like

The `git` type for `externals`, so that:

```TOML
[".oh-my-zsh"]
    # uses git to download
    type = "git"
    
    # url could also be whatever the user prefer, such as ssh://
    url = "https://github.com/ohmyzsh/ohmyzsh"
    
    ## some options could be
    
    # the branch should default to the default branch
    branch = "master"

    # allows faster first clone (especially useful for ephemeral environments)
{{ if .is_devcontainer -}}
    depth = 1
{{ end -}}

    # do the needful for cleaning up the git repo if it exists (`git clean -fdx && git reset --hard origin/$branch` for example)
    clean = "force" # options could be: true (but not forcefully -- would stop or whatever in case it cannot cleanup), false (don't do anything for trying to cleanup)

    # some way to set if we want chezmoi to always try to pull changes for this repo, or let it off for relying on --refresh-externals
    pull = "always"

    ## git clone speeds can be further optimized with some options like so

    # --single-branch
    singleBranch = true # but is already implied by git when using depth

    # --no-tags
    tags = false

    # clones only subdirectory (through git clone --filter and so: https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/)
    filterDirs = "important-directory"
    
    # optimize for ephemeral envs(like chezmoi init --one-shot)
{{ if .is_devcontainer -}}
    oneShot = true # same as depth = 1, tags = false, singleBranch = true
{{ end -}}
```

## Describe alternatives you've considered

I'm using `antigen` for that, but it's only applicable for ZSH modules (I guess). I could easily drop the dependency on `antigen` in my dotfiles if I had such feature, which is especially meaningful as it is a step that is always run even in ephemeral environments (Codespaces, Remote Containers). It would prevent me from having to install Antigen, which mean less one call to an external server.
