### ISSUE TITLE
decode option for chezmoi external

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1429]
## Is your feature request related to a problem? Please describe.

Chezmoi's external feature is quite useful for downloading files directly from GitHub. However, Gitiles (the repository browser which Gerrit provides by default) does not have the option to download the raw file decoded already. It has only an option to download it encoded with base64. And many companies (apart from Google which uses Gerrit extensively for Chromium and AOSP) uses Gerrit.

For example: https://review.gerrithub.io/plugins/gitiles/felipecrs/gerrit-jenkins/+/refs/heads/master/azure-pipelines.yml

It can be downloaded using the query parameter `format=TEXT`. On command line we handle it quite easily:

```console
curl -fsSL https://review.gerrithub.io/plugins/gitiles/felipecrs/gerrit-jenkins/+/refs/heads/master/azure-pipelines.yml?format=TEXT \
  | base64 -d
``` 

But chezmoi external lacks the option to decode it.

## Describe the solution you'd like

```toml
["azure-pipelines.yml"]
    type = "file"
    decode = "base64"
    url = "https://review.gerrithub.io/plugins/gitiles/felipecrs/gerrit-jenkins/+/refs/heads/master/azure-pipelines.yml?file=TEXT"
```

This is just an example, I know that `azure-pipelines.yml` plays no role in a dotfile. :)

## Describe alternatives you've considered

Instead of using chezmoi's external, I can use a script.

**Comment by twpayne** [comment]
I've implemented this slightly differently but with more pluggable functionality in #1435. Instead of using a fixed set of functions, you can specify an arbitrary command and args to filter the data. For the base63 decode case, it looks like (in YAML):

```yaml
azure-pipelines.yml:
    type: file
    url: "https://review.gerrithub.io/plugins/gitiles/felipecrs/gerrit-jenkins/+/refs/heads/master/azure-pipelines.yml?file=TEXT"
    filter:
        command: base64
        args: ["-d"]
```
