### ISSUE TITLE
Add rate-limited automatic refresh of externals

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#1450]
## Is your feature request related to a problem? Please describe.

chezmoi's externals are only refreshed when the user specifies the `-R`/`--refresh-externals` flag. This means that users who want the absolute latest version every time (e.g. @felipecrs [in this comment](https://github.com/twpayne/chezmoi/issues/1421#issuecomment-925380646)) need to pass the `-R` flag every time. On the other hand, refreshing externals every time is slow as chezmoi re-downloads the external archive/file each time, even if it has not changed.

## Describe the solution you'd like

A per-external refresh period setting in `.chezmoiexternals.<format>`, e.g.

```toml
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    refreshPeriod = "1h"
    stripComponents = 1
```

would mean that the external is refreshed automatically at most once per hour. For this, chezmoi will have to store the time of the last refresh for each external, and possibly other HTTP cache-related content (e.g. `Etag`).

The default refresh period of zero would mean never refresh automatically, only refresh on demand, i.e. maintain the current behavior.

## Describe alternatives you've considered

* Having a single global refresh period setting, but fine-grained control is more likely needed.
* Embed git commit hashes in the external URLs and have an external program refresh them ([suggested by @felipecrs](https://github.com/twpayne/chezmoi/issues/1421#issuecomment-925380646)).

## Additional context

None.
