### ISSUE TITLE
Run `.chezmoiexternal` after `run_before` but before everything else

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1616]
## Is your feature request related to a problem? Please describe.

`chezmoiexternal`s provides a way to fetch files that are not in the source state. However, during templates, we might want to deal with some of these externally defined files, and we need to assume that these files would be created before the other templates get executed.

For the rest of the files, they would indeed exist before anything else, as they would be source state. This is the reason why this exception should be applied for `chezmoiexternal`.

## Describe the solution you'd like

In order for that to work, chezmoiexternal should run before everything else (but still after `run_before`).

## Describe alternatives you've considered

It's lucky that alphabetically chezmoiexternal is already one of the first letters, so for most cases this would not be noticed.

## Additional context

Here is an example:

```yaml
# .chezmoiexternal.yaml

".deno/bin/deno":
  type: file
  url: "https://github.com/denoland/deno/releases/download/v1.16.1/deno-x86_64-unknown-linux-gnu.zip"
  executable: true
  filter:
    command: zcat
```

Here is a template which would depend on it:

```
{{- output (joinPath .chezmoi.homeDir ".deno/bin/deno") "completions" "zsh" -}}
```

But as mentioned, luckly, this doesn't trigger the problem.
