### ISSUE TITLE
New template function for capturing the output of the `template` function

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1619]
## Is your feature request related to a problem? Please describe.

I have:

```console
❯ cat ~/.dotfiles/home/.chezmoitemplates/get-latest-github-release
{{- $url :=  printf "https://github.com/%s/releases/latest" . -}}
{{- output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" $url | trim | base -}}
```

And I would like to use it like so:

```console
❯ cat ~/.dotfiles/home/.chezmoiexternal.yaml
{{ $denoVersion := template "get-latest-github-release" "denoland/deno" -}}
".deno/bin/deno":
  type: file
  url: "https://github.com/denoland/deno/releases/download/{{ $denoVersion }}/deno-x86_64-unknown-linux-gnu.zip"
  executable: true
  filter:
    command: zcat
```

But it's not possible, because:

```console
$ chezmoi execute-template '{{ $denoVersion := template "get-latest-github-release" "denoland/deno" }}{{ $denoVersion }}'
chezmoi: template: arg1:1: unexpected <template> in command
```

EDIT 1: I previously posted with the wrong error message above, which turns to be valid but posterior to the error originally reported, as pointed by @twpayne at [here](https://github.com/twpayne/chezmoi/issues/1619#issuecomment-967649423).

EDIT 2: In the variable assignment, it was missing `:` before `=` as pointed by @twpayne at [here](https://github.com/twpayne/chezmoi/issues/1619#issuecomment-967688720). But that wasn't the cause of the issue, anyway.

## Describe the solution you'd like

A function which would let me do that, as pointed in https://stackoverflow.com/a/40170999/12156188. So that I could do:

```console
$ chezmoi execute-template '{{ $denoVersion := execTemplate "get-latest-github-release" "denoland/deno" }}{{ $denoVersion }}'
v1.16.1
```

## Describe alternatives you've considered

I could not find any.

## Additional context

My dotfiles is currently bloated with a lot of code duplication, and now I'm trying to clean it up by using some templates.

**Comment by twpayne** [comment]
> But it's not possible, because:
> 
> ```
> $ chezmoi execute-template '{{ $denoVersion = template "get-latest-github-release" "denoland/deno" }}{{ $denoVersion }}'
> chezmoi: /home/felipecrs/.dotfiles/home/.chezmoiexternal.yaml: template: /home/felipecrs/.dotfiles/home/.chezmoiexternal.yaml:46: unexpected <template> in command
> ```

This is likely because chezmoi reads files in alphabetical order, so it reads `.chezmoiexternals.<format>` before reading the `.chezmoitemplates` directory, so the templates are not available when the `.chezmoiexternals.<format>` template is executed. There's actually [an existing comment buried in the code about this](https://github.com/twpayne/chezmoi/blob/master/internal/chezmoi/sourcestate.go#L722-L727).

I think the correct fix here is for chezmoi to change the order in which it reads files. Specifically, it should read `.chezmoidata` and `.chezmoitemplates` before anything else.

**Comment by felipecrs** [comment]
I don't think it's the case:

![image](https://user-images.githubusercontent.com/29582865/141540361-a7852f2c-49df-44d3-83d8-5ed4fea865f5.png)

**Comment by felipecrs** [comment]
Oh sorry, I wrote the issue wrongly. I fixed it now. The correct error message is:

```console
$ chezmoi execute-template '{{ $denoVersion = template "get-latest-github-release" "denoland/deno" }}{{ $denoVersion }}'
chezmoi: template: arg1:1: unexpected <template> in command
```

**Comment by felipecrs** [comment]
But you are right, even if I could do what I wanted, I would then face this second issue. And I do agree with you that `.chezmoidata` and `.chezmoitemplates` should be read before.

**Comment by twpayne** [comment]
Re
```
chezmoi execute-template '{{ $denoVersion = template "get-latest-github-release" "denoland/deno" }}
```
I think it needs to be `:=` as a new variable is being introduced, not `=`.

**Comment by felipecrs** [comment]
You are absolutely right, but it fails with the same output after fixing.

**Comment by twpayne** [comment]
Please don't edit GitHub comments (especially other people's) unless they contain something really bad for a couple of reasons:
1. After editing, it makes comments like [this one](https://github.com/twpayne/chezmoi/issues/1619#issuecomment-967688720) make no sense, which makes it hard for people reading the conversation to understand it.
2. GitHub does not send an "updated comment" email when a comment is edited, so people reading GitHub notifications via email (like me) will see and may respond to the original comment, not the edited one.
It's totally OK to make mistakes in public (I have made many, and continue to make many), and re-writing history to hide the mistake makes things confusing for all involved :)

**Comment by felipecrs** [comment]
Again, you are totally right. And I just noticed now that I even edited your own comment!

1. A real mistake of me, and
2. Lack of attention.

I reverted my comments and I edited the Issue description with notes, because my original goal was to actually try not to confuse people what was the truthy goal of this Issue.

**Comment by felipecrs** [comment]
@twpayne, I think this needs to be kept open, as there isn't yet a function for the described use.

**Comment by felipecrs** [comment]
```console
❯ /tmp/tmp.6JutSK7iYw/chezmoi --version
chezmoi version v2.7.5-SNAPSHOT-90120fe2, commit 90120fe23a2d0e555aeb96c2c710f3490d9e0cda, built at 2021-11-20T14:42:28Z, built by goreleaser

❯ /tmp/tmp.6JutSK7iYw/chezmoi execute-template '{{ $denoVersion := template "get-latest-github-release" "denoland/deno" }}{{ $denoVersion }}'
chezmoi: template: arg1:1: unexpected <template> in command
```

**Comment by twpayne** [comment]
I think `text/template`'s existing `template` function is the existing function that captures the result of a template.

In [this test](https://github.com/twpayne/chezmoi/blob/master/internal/cmd/testdata/scripts/templatedata.txt#L22-L31) I specify some data in `.chezmoidata.<format>`, have a template that uses it in `.chezmoitemplates`, and finally use that template.

If this is not sufficient, could you share an example where it does not work?

**Comment by felipecrs** [comment]
In this very specific example, the only place I would use deno's version would be in a `.chezmoiexternal.yaml` file. Then, I would have to create a variable which would be available globally in `.chezmoidata.yaml` rather than being able to create the variable only in the scope I need.

**Comment by felipecrs** [comment]
But, as you say, it may be sufficient.

**Comment by felipecrs** [comment]
```yaml
# .chezmoidata.yaml

externals:
  deno:
    version: {{ template "get-latest-github-version" "denoland/deno" | quote }}
```

I'm trying to do the above, but it seems that templates are not supported in `chezmoidata`, which means it is not an option for this use case.

**Comment by MuXiu1997** [comment]
in chezmoi 2.8.0, the `gitHubLatestRelease` template function is available and it will cache based on RFCs to avoid duplicate requests

**Comment by felipecrs** [comment]
That's right, it's a possible alternative for the function that I'm writing. But the use case of this feature request is certainly not limited to that.

**Comment by MuXiu1997** [comment]
Here's an interesting solution

`run_before_01-chezmoi-cache.sh.tmpl`
```sh
#!/bin/sh

set -e

chezmoi_cache="/tmp/.chezmoi"
echo '{{ output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/denoland/deno/releases/latest" | trim | base }}' > "$chezmoi_cache/denoVersion"
echo '{{ output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/denoland/deno/releases/latest" | trim | base }}' > "$chezmoi_cache/dockerComposeVersion"
```

`.chezmoiexternal.yaml`
```yaml
".deno/bin/deno":
  type: file
  url: "https://github.com/denoland/deno/releases/download/{{ include "/tmp/.chezmoi/denoVersion" }}/deno-x86_64-unknown-linux-gnu.zip"
  executable: true
  filter:
    command: zcat

".docker/cli-plugins/docker-compose":
  type: file
  url: "https://github.com/docker/compose/releases/download/{{ include "/tmp/.chezmoi/dockerComposeVersion" }}/docker-compose-linux-x86_64"
  executable: true
```

`run_after_99-clear-chezmoi-cache.sh.tmpl`
```sh
#!/bin/sh

set -e

rm -rf /tmp/.chezmoi
```

More optimization can be done on this basis

**Comment by MuXiu1997** [comment]
@felipecrs  Here's an interesting solution
`run_before_01-chezmoi-cache.sh.tmpl`
```sh
#!/bin/sh

set -e

chezmoi_cache="/tmp/.chezmoi"
mkdir -p "$chezmoi_cache"
echo '{{ output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/denoland/deno/releases/latest" | trim | base }}' > "$chezmoi_cache/denoVersion"
echo '{{ output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/docker/compose/releases/latest" | trim | base }}' > "$chezmoi_cache/dockerComposeVersion"
```

`.chezmoiexternal.yaml`
```yaml
".deno/bin/deno":
  type: file
  url: "https://github.com/denoland/deno/releases/download/{{ include "/tmp/.chezmoi/denoVersion" }}/deno-x86_64-unknown-linux-gnu.zip"
  executable: true
  filter:
    command: zcat

".docker/cli-plugins/docker-compose":
  type: file
  url: "https://github.com/docker/compose/releases/download/{{ include "/tmp/.chezmoi/dockerComposeVersion" }}/docker-compose-linux-x86_64"
  executable: true
```

`run_after_99-clear-chezmoi-cache.sh.tmpl`
```sh
#!/bin/sh

set -e

rm -rf /tmp/.chezmoi
```
More optimization can be done on this basis
