### ISSUE TITLE
Add some templateFunc about githubRepo

### ISSUE THREAD

**Issue by MuXiu1997** [twpayne/chezmoi#1632]
## Is your feature request related to a problem? Please describe.

I feel some inconvenience when I managed some plugins such as oh-my-zsh plugin or ranger plugin with `.chezmoiexternal` .

  - A plugin is usually a github repo, and I may need to do a lot of repetitive work when I'm writing `.chezmoiexternal`

  - I can't seem to get the url of the latest release easily

hence I would like `chezmoi` to provide a templateFunc like `gitHubRepo` to get some information about the github repo.

## Describe the solution you'd like

```yaml
# .chezmoiexternal.yaml

# Oh-my-zsh plugins
{{ $repos := list
    # gitHubRepo <github-repo-fullname> [ref]
    (gitHubRepo "jeffreytse/zsh-vi-mode")
    (gitHubRepo "zsh-users/zsh-syntax-highlighting" "heads/master")
    # assuming it exists
    (gitHubRepo "foo/bar" "heads/main")
-}}
{{ range ($repos) -}}
.oh-my-zsh/custom/plugins/{{ .name }}:
  type: "archive"
  url: "{{ default .archive .latestArchive }}"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
{{ end -}}
```

And output:

```yaml
# .chezmoiexternal.yaml

# Oh-my-zsh plugins
.oh-my-zsh/custom/plugins/zsh-vi-mode:
  type: "archive"
  url: "https://api.github.com/repos/jeffreytse/zsh-vi-mode/tarball/v0.8.5" # latest releases
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/zsh-syntax-highlighting:
  type: "archive"
  url: "https://api.github.com/repos/zsh-users/zsh-syntax-highlighting/tarball/heads/master"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/bar:
  type: "archive"
  url: "https://api.github.com/repos/foo/bar/tarball/heads/main"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
```

## Describe alternatives you've considered

n/a

## Additional context

I love `chezomi`, thank you for everything you've done for this AMAZING project!

and sorry for my poor English~

**Comment by felipecrs** [comment]
I believe a guide here might help. This is how I'm doing:

https://github.com/felipecrs/dotfiles/blob/master/home/.chezmoiexternal.yaml#L46-L52

And there is an issue open to improve the ability of using function-like templates: https://github.com/twpayne/chezmoi/issues/1619

That said, for me, the best benefit of such a function `githubRepo` would be to drop the dependency on `curl` on my templates. However, I would not favor a `githubRepo` function but instead a curl-like one which could be used more generally.

**Comment by felipecrs** [comment]
Also, have in mind that you can achieve a similar level of usability that you are looking for by just using the existing `.chezmoitemplates` and `.chezmoidata` machinery out there.

**Comment by MuXiu1997** [comment]
> I believe a guide here might help. This is how I'm doing:
> 
> https://github.com/felipecrs/dotfiles/blob/master/home/.chezmoiexternal.yaml#L46-L52
> 
> And there is an issue open to improve the ability of using function-like templates: #1619
> 
> That said, for me, the best benefit of such a function `githubRepo` would be to drop the dependency on `curl` on my templates. However, I would not favor a `githubRepo` function but instead a curl-like one which could be used more generally.

Thanks for your reply!
I've seen #1619 before, and if `template` templateFunc could be used in `.chezmoiexternal`, it would indeed solve the problem in a more personal way
But the `gitHubKeys` templateFunc provided at [githubtemplatefuncs.go](https://github.com/twpayne/chezmoi/blob/master/internal/cmd/githubtemplatefuncs.go#L13) can also be replaced by `curl`
So I don't think it's bad to provide an additional convenience

**Comment by MuXiu1997** [comment]
> I believe a guide here might help. This is how I'm doing:
> 
> https://github.com/felipecrs/dotfiles/blob/master/home/.chezmoiexternal.yaml#L46-L52
> 
> And there is an issue open to improve the ability of using function-like templates: #1619
> 
> That said, for me, the best benefit of such a function `githubRepo` would be to drop the dependency on `curl` on my templates. However, I would not favor a `githubRepo` function but instead a curl-like one which could be used more generally.

In fact, I tried to solve it with `template` templateFunc a few days ago and found the same problem #1619
That's why I wanted to solve it in a more convenient way

**Comment by felipecrs** [comment]
Well, in your case specifically isn't simpler to just do the following?

```yaml
{{ range $_, $repo := list "jeffreytse/zsh-vi-mode" "zsh-users/zsh-syntax-highlighting" "foo/bar" -}}
.oh-my-zsh/custom/plugins/{{ .name }}:
  type: "archive"
  url: "https://github.com/{{ $repo }}/archive/HEAD.zip"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
{{ end -}}
```
