### ISSUE TITLE
`toYaml` template function

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1650]
## Is your feature request related to a problem? Please describe.

I'm now handling some YAML files, and a `toYaml` function would come very in handy.

## Describe the solution you'd like

The same `toYaml` function which Helm provides to templates.

## Describe alternatives you've considered

To not use YAML, but instead JSON.

## Additional context

https://github.dev/helm/helm/blob/dd0177aed71dd3c5b044e25c55870cd66f0f05fa/pkg/engine/funcs.go#L88

It may be worth to add some more functions that helm adds too, like `toToml`, `fromYaml`, etc.

**Comment by felipecrs** [comment]
My specific use case, in case you wonder, is:

`home/private_dot_config/private_chezmoi/private_root.config.yaml.tmpl`:

```yaml
sourceDir: {{ joinPath .chezmoi.sourceDir "root" | quote }}
destDir: "/"

{{ $chezmoiData := unset . "chezmoi" }}

data:
  {{ .chezmoi.data | toYaml | indent 2 }}
```

But of course it shouldn't be limited to that.
