### ISSUE TITLE
Need a description of how to use a variable value in the definition of another variable

### ISSUE THREAD

**Issue by pwm1234-sri** [twpayne/chezmoi#1878]
I struggled for a while trying to use the value of one variable in the  definition of another variable. For example:

```yaml
data:
    diff_command: '/path/to/my_favorite_diff_tool'

diff:
    command: '{{ .diff_command }}'
```

This seems to work with a toml config file, but not with a yaml config file. 
I also try using yaml anchors (as described in the yaml spec, https://yaml.org/spec/1.2-old/spec.html#id2760395, example 2.10), 
but that did not work either. Then I stumbled upon https://github.com/benmezger/dotfiles/blob/main/.chezmoi.yaml.tmpl and that works, but I have not seen it described in the chezmoi documents (at least the ones I have looked at and remembered).

I am not trying to be nit-picky, but this is something I struggled with and thought it would be helpful to have in the chezmoi documentation, which seems to be quite good. 
Thanks for making chezmoi available!
