### ISSUE TITLE
Filter multiple files from `.chezmoiexternal` archive

### ISSUE THREAD

**Issue by latipun7** [twpayne/chezmoi#1938]
## Is your feature request related to a problem? Please describe.

I'd like to get the specific files / folders from archive. `.chezmoiexternal` already has `filter.*` field, but it seems only work for single file and for `type: file`.
I tried this, but not work (yaml):
```yaml
www/adminer/plugins:
  type: archive
  url: https://api.github.com/repos/vrana/adminer/tarball
  refreshPeriod: 744h
  stripComponents: 2
  filter:
    command: tar
    args: ["--extract", "--gzip", "--file", "/dev/stdin", "--to-stdout", "--wildcards", "*/plugins/*.php"]
```

## Describe the solution you'd like

Allow `filter` on `type: archive`.

## Describe alternatives you've considered

Perhaps a new option could be added to chezmoi to help filter the files in a more abstracted way (thus allowing the same in .zip files regardless of the platform). Something like:
```yaml
www/adminer/plugins:
  type: archive
  url: https://api.github.com/repos/vrana/adminer/tarball
  refreshPeriod: 744h
  files: ["*/plugins/*.php", "*/readme.txt"]
```

## Additional context

On terminal, I could do this and get the specific files (all `*.php` files inside `plugins` folder and its subdirectories) and extracted in the current directory:
```bash
curl -fsLS https://api.github.com/repos/vrana/adminer/tarball | tar --extract --gzip --file /dev/stdin --strip-components=2 --wildcards '*/plugins/*.php'
```
🙇

**Comment by twpayne** [comment]
In the short term, this should be possible using `.chezmoiignore`. Something like the following should work:

```
www/adminer/plugins/** # ignore everything by default...
!www/adminer/plugins/*.php # ...except for *.php files
```

Note that I haven't tested this.

**Comment by latipun7** [comment]
I tested it, it didn't work. It's not copying anything (all ignored)

https://api.github.com/repos/vrana/adminer/tarball more or less has this folder structure:
```
.
├── .github
├── adminer
├── designs
├── plugins
├── .../
├── .gitignore
├── .gitmodules
├── readme.txt
└── ...
```
Since I just want only `plugins` folder but only for `*.php` files, I set this following in `.chezmoiexternal.yml`
```yml
www/adminer:
  type: archive
  url: https://api.github.com/repos/vrana/adminer/tarball
  stripComponents: 1
  refreshPeriod: 744h
```
then use this in `.chezmoiignore`
```ignore
www/adminer/**
!www/adminer/plugins/*.php
```
but nothing copied. All ignored, the `plugins` folder not available.

**Comment by twpayne** [comment]
#1941 implements this. With this, your external would look like:

```yaml
www/adminer/plugins:
    type: archive
    url: https://api.github.com/repos/vrana/adminer/tarball
    refreshPeriod: 744h
    stripComponents: 2
    include:
    - "*"
    - "*/plugins"
    - "*/plugins/**"
```
