### ISSUE TITLE
data render from chezmoi.yaml.tmpl are lower case

### ISSUE THREAD

**Issue by dhruvinsh** [twpayne/chezmoi#1972]
## Describe the bug

I have chezmoi.yaml.tmpl to generate some data based on answers to the questions. Which can be seen by `chezmoi data`. But the key always render in lowercase and disregard the original variable's camelCase.

## To reproduce

Steps to reproduce the behavior"
```yaml
{{ $personalMachine := promptBool "Is it personal machine" -}}

data:
    personalMachine: {{ $personalMachine }}
```
once performed chezmoi init answered to the question,  data generate as below
```
chezmoi init
```json
{
  .,
  .,
  "personalmachine": true,
  .,
  .,
}
```
## Expected behavior

Data should have original variable name with intact case, that means it should be "personal**M**achine" not "personal**m**achine"
