### ISSUE TITLE
Add ability to specify extra flags for keepassxc-cli

### ISSUE THREAD

**Issue by isindir** [twpayne/chezmoi#2002]
## Feature request description

Is your feature request related to a problem? `yes`

I'm trying to use `keepassxc-cli` integration with yubikey protection and it does not work. What is missing is `-y <slot>:<serial>` missing from the command issued by `chezmoi`. 

## Describe the solution you'd like

I'd like to see a configuration feature, where I'd be able to specify extra flags to `keepassxc-cli` configuration file. And I'd like potentially to specify multiple `-y <slot>:<serial>` flags, so that I can use different hardware keys with the same database without having special configs and remember where to use which key (multiple `-y` are not yet supported by kepassxc as of version 2.7.1, but I have raised separate [ticket](https://github.com/keepassxreboot/keepassxc/issues/7847) with the project).

How the potential solution could look like, various options in `~/.config/chezmoi/chezmoi.yaml` file:

> preffered:
```yaml
...
keepassxc:
  extra_args: "-y <slot>:<serial> -y <slot>:<serial>"
  database: "<full_path>/<file_name>.kdbx"
...
```

```yaml
...
keepassxc:
  yubikeys:
    - "<slot>:<serial>"
    - "<slot>:<serial>"
    - ...
  database: "<full_path>/<file_name>.kdbx"
...
```

```yaml
...
keepassxc:
  yubikey: "<slot>:<serial>"
  database: "<full_path>/<file_name>.kdbx"
...
```

## Describe alternatives you've considered

I've tried following config, but it fails as the whole string was interpreted as db file name:

```yaml
...
keepassxc:
  database: "<full_path>/<file_name>.kdbx -y <slot>:<serial>"
...
```

**Comment by twpayne** [comment]
The `keepassxc.args` [configuration variable](https://www.chezmoi.io/reference/configuration-file/variables/) already exists, but I see that it is not mentioned in the `keepassxc*` template function documentation. I'll update the documentation.

In the immediate term you can use:

```yaml
keepassxc:
  args:
    - "-y"
    - "<slot>:<serial>"
    - "-y"
    - "<slot>:<serial>"
```
