### ISSUE TITLE
Not being able to encrypt files with GPG

### ISSUE THREAD

**Issue by delucca** [twpayne/chezmoi#2221]
## Describe the bug

I've followed the steps [under Chezmoi's GPG docs](https://www.chezmoi.io/user-guide/encryption/gpg/#asymmetric-privatepublic-key-encryption) to enable GPG encryption. My `chezmoi.toml` file looks like this:

```toml
sourceDir = "/home/delucca/.dotfiles/configs/chezmoi"
encryption = "gpg"

[gpg]
  recipient = "3D919D86E30F08482759B20378C152CA626C94A0"
  symmetric = true
```

And, this is my pubring

```
/home/delucca/.gnupg/pubring.kbx
--------------------------------
pub   ed25519/0x78C152CA626C94A0 2022-04-17 [C]
      Key fingerprint = 3D91 9D86 E30F 0848 2759  B203 78C1 52CA 626C 94A0
uid                   [ultimate] Daniel De Lucca <------->
uid                   [ultimate] Daniel De Lucca <------->
uid                   [ultimate] Daniel De Lucca <------->
sub   ed25519/0x992280BF6FB2EE80 2022-04-17 [S] [expires: 2023-04-17]
sub   cv25519/0x0E141355C2CE0F4C 2022-04-17 [E] [expires: 2023-04-17]
sub   ed25519/0x93CE9ED39743CCCF 2022-04-17 [A] [expires: 2023-04-17]
```
(I've removed the e-mail addresses for privacy reasons)

Them, when I run `chezmoi add --encrypt <file-path>` I receive a prompt to insert a passphrase, instead of it simply using the expected GPG key.

For example, running:
```
chezmoi add --encrypt ~/.aws/config
```

My pinentry program appears to create a pin.

While, if I run:

```
gpg --armor --encrypt --recipient 3D919D86E30F08482759B20378C152CA626C94A0 < ~/.aws/config
```

It generates an exncrypted file, as expected.

What should I do? Thanks :)
