### ISSUE TITLE
[feat] Move `Source state attributes` to `Source state config`

### ISSUE THREAD

**Issue by loynoir** [twpayne/chezmoi#2293]
## Is your feature request related to a problem? Please describe.

I think this root cause of [issues/2292](https://github.com/twpayne/chezmoi/issues/2292) is to guess what is the original filename.

Besides, under `Source state attributes` implement, I can't use `meld ~ REPODIR`.

## Describe the solution you'd like

```sh
$ tree -a .
.
├── .chezmoiroot
└── home
    ├── .bash_history
    └── .chezmoistate
```
```txt
# .chezmoiroot
home
```

```yaml
# .chezmoistate
state_attributes:
  .bash_history:
    modify: true
    private: true
```

## Does any other dotfile manager use similar pattern?
Yes, `dotdrop` has a  config.yml describe permission stuff.

```yaml
dotfiles:
  f_apprc:
    src: apprc
    dst: ~/.apprc
    chmod: "600"
```

## Additional context
Manage dotfiles in alpine devcontainer.

Migrate from `dotdrop` which not in official repo and depends on python, 

To `chezmoi` which in official repo and have zero dependency, awesome!
