### ISSUE TITLE
Support multiple archives for a single `.chezmoiexternal` entry

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#2549]
## Is your feature request related to a problem? Please describe.

I want to install both `kubectx` and `kubens` into `~/.local/bin`. However, they are distributed as archives, and currently chezmoi doesn't support extracting multiple archives into a single dir.

## Describe the solution you'd like

I guess something like below

```yaml
# .chezmoiexternal.yaml

".local/bin":
  - type: archive
    url: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_x86_64.tar.gz"
    include:
      - kubectx
  - type: archive
    url: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubens_v0.9.4_linux_x86_64.tar.gz"
    include:
      - kubens
```

EDIT: I had previously reported an issue with the above alternative, but it was my mistake. I was using `archive` instead of `file`.

And chezmoi would either:

1. Merge contents giving preference to the last one
2. Error out if there are colliding files

## Describe alternatives you've considered

```yaml
".local/bin/kubectx":
  type: file
  url: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx_v0.9.4_linux_x86_64.tar.gz"
  filter:
    command: tar
    args: ["--extract", "--gunzip", "--to-stdout", "kubectx"]
  executable: true
".local/bin/kubens":
  type: file
  url: "https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubens_v0.9.4_linux_x86_64.tar.gz"
  filter:
    command: tar
    args: ["--extract", "--gunzip", "--to-stdout", "kubens"]
  executable: true
```

## Additional context

None.
