### ISSUE TITLE
Can't use a github action to verify script because prompt requires `TTY`

### ISSUE THREAD

**Issue by arran4** [twpayne/chezmoi#2595]
## Describe the bug

I am trying to use this github action:
```
name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          yes "" | sh -c "$(curl -fsLS get.chezmoi.io)" -- init --debug --force --apply arran4
```

To verify the script as I often put changes directly in github 

However I get this error:
```
chezmoi: template: chezmoi.toml:7:17: executing "chezmoi.toml" at <promptBool "headless" $headlessGuess>: error calling promptBool: open /dev/tty: no such device or address
```

https://github.com/arran4/dotfiles/actions/runs/3528532579/jobs/5918736477

However I believe that my defaults are sane and I just want it to accept my defaults, hence the:
```
          yes "" | 
```

At the start of the script.

I am not sure what flags - if there is one - would allow me tell it to "accept all defaults"

## To reproduce

Run:
```
name: CI

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          yes "" | sh -c "$(curl -fsLS get.chezmoi.io)" -- init --debug --force --apply arran4

```

In a github action

## Expected behavior

Errors that actually relate to errors in my script. Hence why I have avoided:
```
  -k, --keep-going                     Keep going as far as possible after an error
```

As by the sounds of it, it might ignore errors I want to pick up on

## Output of command with the `--verbose` flag

n/a

## Output of `chezmoi doctor`

n/a

## Additional context

n/a
