### ISSUE TITLE
Support ".tmpl" suffix for .chezmoiexternal files

### ISSUE THREAD

**Issue by cglong** [twpayne/chezmoi#2628]
## Is your feature request related to a problem? Please describe.

I don't like how source editors and syntax highlighters see the extension in [my `.chezmoiexternal.toml` file](https://github.com/cglong/dotfiles/blob/5060d733ecb44a6f89ad4f8fd4bc6c69e2d7845a/home/.chezmoiexternal.toml) and interpret the templating syntax as invalid.

## Describe the solution you'd like

I wish I could add a `.tmpl` extension to this file (i.e. `.chezmoiexternal.toml.tmpl`) to make it clear that it doesn't contain valid TOML. Behavior of the file would be unchanged, with or without the suffix.

If this is already supported today, could a note be added to the docs?

## Describe alternatives you've considered

Just using `.toml` works; it's just a little more cumbersome to use 🙂

## Additional context

An example of GitHub's highlighting behavior:

```toml
[".iterm2"]
    type = "archive"
    url = "https://github.com/gnachman/iTerm2-shell-integration/archive/main.tar.gz"
    stripComponents = 2
    refreshPeriod = "168h"
    include = [
{{ range .iTermUtilities }}
        "*/utilities/{{ . }}",
{{ end }}
```
