### ISSUE TITLE
Also git-repo externals to add only a subdirectory of the repo

### ISSUE THREAD

**Issue by mew1033** [twpayne/chezmoi#2678]
## Is your feature request related to a problem? Please describe.

I see that git-repo externals were added in #1911, which is awesome. Thank you! What I'd like to see is a way to specify a specific folder from the git repo as the "root" to add to the target. As an example, I want to add this docker completion module: https://github.com/matt9ucci/DockerCompletion#other-methods. The module code itself is contained within a subdirectory of that repo (see the `As a "well-formed" module` section).

## Describe the solution you'd like

It'd be great if chezmoi could pick a single folder from the repo of a git-repo external and discard the rest.

**Comment by twpayne** [comment]
This  would be hard to implement, but there are two existing workarounds:

Firstly, you can use GitHub-generated archives with an `include` filter, instead of a git repo:

```toml
["path/where/PowerShell/installs/completions/DockerCompletion"]
    type = "archive"
    url = "https://github.com/matt9ucci/DockerCompletion/archive/refs/heads/master.zip"
    stripComponents = 2
    include = ["DockerCompletion-master/DockerCompletion/**"]
    refreshPeriod = "168h"
```

Secondly, you could write a script that uses [`git sparse-checkout`](https://www.git-scm.com/docs/git-sparse-checkout).
