### ISSUE TITLE
Option to not make github API requests when it's not needed

### ISSUE THREAD

**Issue by mkalinski** [twpayne/chezmoi#2725]
## Is your feature request related to a problem? Please describe.

When I work with my configuration files, I often like to make a quick tweak, do a `chezmoi apply`, see the results, tweak again, apply again, and so on.

Lately, I've started using externals, with `gitHubLatestRelease` to automatically upgrade a tool I'm using. But with my workflow of often calling `chezmoi apply`, I've been running into github's rate limiting.

I know the usual answer to issues with rate limiting seems to be "connect an API token to lift the limit", but I think it's a wrong solution in my particular case. I just find chezmoi's current behaviour slightly wrong.

Let's assume I had the following external configured:

```toml
['example/bin/chezmoi']
type = 'file'
url = 'https://github.com/twpayne/chezmoi/releases/download/{{ (gitHubLatestRelease "twpayne/chezmoi").TagName }}/chezmoi-linux-amd64'
refreshPeriod = '24h'
```

(I don't update chezmoi this way, this is just a hypothetical.)

Because of `refreshPeriod`, the download has no chance of running more often than once a day. However, every time I do `chezmoi apply`, the `.chezmoiexternal.toml` file gets evaluated, and `gitHubLatestRelease` is called, causing unnecessary web requests, and eventually rate limiting.

Of course, the problem is that chezmoi needs to evaluate the template functions in `.chezmoiexternal.toml` before it can read its contents and interpret the `refreshPeriod` value. But from the user perspective, this is a bit frustrating, as I feel there really should be an option to let chezmoi know that it shouldn't phone github more often than it's logically necessary.

## Describe the solution you'd like

I'm going to only consider `gitHub*` functions in `.chezmoiexternal` files. I know they could be used in other templates, too, but I feel it's probably really rare, and superfluous to my problem.

I think the least problematic solution would be to add a command line flag that would make chezmoi not touch `.chezmoiexternal` files during a run. Like `--refresh-externals never` but stronger (`--no-externals`?).

It's probably the easiest way to flag that I, as a user, am sure that I need no externals update during this run under any circumstances.

### Passing `refreshPeriod` to `gitHub*` functions as an argument

Since the problem is that template functions need to be evaluated before chezmoi can read the `refreshPeriod` value, perhaps it would help to make these functions aware of the value. Something like `{{ (gitHubLatestRelease "twpayne/chezmoi" "24h").TagName }}`.

Of course, then the problem becomes what should the function evaluate to when it doesn't make a call to github? Should they cache return values between calls? I feel like it's not ideal to ask to make these functions more complicated.

### Lazy alternative to template functions for `.chezmoiexternal`

Some special syntax that would make chezmoi substitute values in the URL only after reading `refreshPeriod` if needed. For example:

```toml
['example/bin/chezmoi']
type = 'file'
url = 'https://github.com/twpayne/chezmoi/releases/download/$GITHUB_LATEST_RELEASE_TAG_NAME/chezmoi-linux-amd64'
refreshPeriod = '24h'
```

It's unfortunately inelegant compared to the template syntax.
