### ISSUE TITLE
.chezmoiroot not working in GitHub Actions

### ISSUE THREAD

**Issue by futabooo** [twpayne/chezmoi#2865]
## Describe the bug

`.chezmoiroot` seems to be ignored when using one line install with GitHub Actions

## To reproduce

add `.chezmoiroot`
```
home
```

add `home/.chezmoiscripts/run_once_echo.sh.tmpl`

```
{{ if eq .chezmoi.os "darwin" -}}
#!/usr/bin/env bash

set -euo pipefail

echo {{ .chezmoi.sourceDir }}

{{ end -}}

```

add `.github/workflows/test.yaml`
```
name: Test install

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub UseName'
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Run install
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply ${{ inputs.username }} 
```

when dispatch Test install workflow, echo `/Users/runner/.local/share/chezmoi`

## Expected behavior

echo `/Users/runner/.local/share/chezmoi/home`
