### ISSUE TITLE
"invalid header" using .chezmoiexternal to extract single file

### ISSUE THREAD

**Issue by ckt114** [twpayne/chezmoi#3077]
## Describe the bug
I followed the instructions under `Extract a single file from an archive` on [this page](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#include-a-single-file-from-a-url) to download OTEL collector and only picking out `otelcol-contrib` from the archive but chezmoi is throwing the error below.

**Error**
```
chezmoi: .bin/otelcol-contrib: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.76.1/otelcol-contrib_0.76.1_darwin_arm64.tar.gz: gzip: invalid header
```

## To reproduce
1. Add content below to `.chezmoiexternal.yaml`
   ```yaml
   .bin/otelcol-contrib:
     type: archive
     url: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.76.1/otelcol-contrib_0.76.1_darwin_arm64.tar.gz
     executable: true
     filter:
       command: tar
       args: ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "otelcol-contrib"]
   ```
1. Apply with `chezmoi apply -v`

## Expected behavior
There should be a file at `~/.bin/otelcol-contrib`

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```
It produces the same error with verbose flag.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

## Additional context

I've downloaded the file using `wget` and then `tar xfv` it and the file is indeed extracted to the current folder, not inside a subfolder so the format should be correct. I tried `otelcol-contrib/otelcol-contrib` as the last item in `filter.args` as well but that didn't work either. I've also added `format: tar.gz` but still same error.
