### ISSUE TITLE
Allow `executable` used on `archive-file` type

### ISSUE THREAD

**Issue by latipun7** [twpayne/chezmoi#3100]
## Describe the bug

_I don't know this is the intentional or not, so I'm not sure this is bug report or feature request 😅_

Since `archive-file` external type is kind of `file` type, `executable` should works too.

## To reproduce

- here's my `.chezmoiexternal.yml`:
  ```yml
	.local/bin/fnm:
		type:  archive-file
		url: {{ template "fnm-download-url" . }}
		path: fnm
		executable: true
		refreshPeriod: 132h
	```
- `chezmoi apply -v`
- file `.local/bin/fnm` didn't have executable permission (the original archive file does not have executable permission, that's why I want to set it as executable with `executable` field).

## Expected behavior

Extracted files should have executable permission.

---

Tell me if you need more info. Thank you 🙏
