### ISSUE TITLE
Add dynamic scriptEnv

### ISSUE THREAD

**Issue by NavyD** [twpayne/chezmoi#3101]
## Is your feature request related to a problem? Please describe.

When using py scripts, it is usually executed in the venv environment. it is necessary to configure the scriptEnv PATH environment variable for the py script to run in venv. Now, the PATH variable must be determined during chezmoi init. Once the venv environment changes, it must be reinit to take effect

## Describe the solution you'd like

The scriptEnv in the configuration file is processed as a template at runtime, such as

```toml
[scriptEnv]
PATH = '{{`path/to/venv/bin:{{env "PATH"}}`}}'
```

## Describe alternatives you've considered

Currently, the env variable PATH can only be fixed during init

```toml
[scriptEnv]
# {{- $venv_home := joinPath .chezmoi.sourceDir ".venv" }}
PATH = '{{$venv_home}}/bin{{ternary ";" ":" $is_win}}{{env "PATH"}}'
VIRTUAL_ENV = '{{$venv_home}}'
PYTHONHOME = ''
```

**Comment by twpayne** [comment]
I don't fully understand what you want here.

If I understand correctly:
1. You have a Python virtual env which is in the `.venv` directory of your source directory, e.g. `~/.local/share/chezmoi/.venv`.
2. You want the `bin` subdirectory of this `.venv` directory, i.e. `~/.local/share/chezmoi/.venv/bin` to be the first element of `$PATH` when chezmoi runs scripts.

What I don't understand is:

> Once the venv environment changes, it must be reinit to take effect

What exactly do you mean by "the venv environment changes"? What changes exactly?

**Comment by NavyD** [comment]
I apologize for the confusion caused by the wrong description

I am using a venv created with [poetry](https://python-poetry.org/) in the `~/.local/share/chezmoi/.venv` directory, but simply relying on chezmoi itself cannot make the `.chezmoiscripts/*.py` scripts run in the .venv environment. They can only run properly after activating .venv and then running `chezmoi apply`. The `interpreters.py=.venv/bin/python3` [interpreters](https://www.chezmoi.io/reference/target-types/#scripts-on-windows) configuration provided by chezmoi is ineffective on Linux. 

It is convenient to activate venv using `scriptEnv` in chezmoi without external handling for `.chezmoiscripts/*.py`. Otherwise, it may be necessary to rely on shell encapsulation of chezmoi, such as configuring alias, shim, etc.

It now appears that specifying the `PATH` variable in `scriptEnv` is a foolish behavior. Fixing the `PATH` variable will affect many commands executed in chezmoi, such as `prehook, merge.command,.chezmoiscripts`, etc., causing related script,commands to be unable to inherit the current `PATH` environment variable in chezmoi. 

If you want [merge](https://www.chezmoi.io/reference/commands/merge/) to dynamically choose between `vscode` and `vimdiff`, you can use the following configuration in `chezmoi.toml.tmpl`. When `scriptEnv.PATH` is configured and `chezmoi init` is used without vscode in the environment, `chezmoi merge $target` will be unable to find `code` and will continue to use `vimdiff`, you must rerun `chezmoi init` on the vscode terminal to take effect

```toml
# ...
[scriptEnv]
# {{- $venv_home := joinPath .chezmoi.sourceDir ".venv" }}
PATH = '{{$venv_home}}/bin{{ternary ";" ":" $is_win}}{{env "PATH"}}'
VIRTUAL_ENV = '{{$venv_home}}'
PYTHONHOME = ''
[merge]
command = 'sh'
args = ["-c", """
if command -v code >/dev/null; then 
    exec code --wait --merge "{{`{{ .Destination }}`}}" "{{`{{ .Source }}`}}" "{{`{{ .Target }}`}}" "{{`{{ .Source }}`}}"
else
    exec vimdiff "{{`{{ .Destination }}`}}" "{{`{{ .Source }}`}}" "{{`{{ .Target }}`}}"
fi"""
]
```

If `scriptEnv.PATH` can be generated during runtime in chezmoi, it can avoid the issue of not being able to find code. That's why I need a dynamic env.

If there is any convenient method for `.chezmoiscripts/*.py` to use the venv environment, I hope everyone can share it!!!

Thank you very much for your attention and for creating such a great software
