### ISSUE TITLE
Frontmatter support in template source files

### ISSUE THREAD

**Issue by zacwest** [twpayne/chezmoi#3206]
## Is your feature request related to a problem? Please describe.

Some of my data files are separated from the templates which use them; I'd like to colocate them.

## Describe the solution you'd like

Allow me to specify frontmatter (using --- for YAML, +++ for TOML, there may be other standards?), for example a match config for Espanso:

```
# collapsed for brevity in example
greek_alphabet: [{alpha: α}, {beta: β}, {chi: χ}, {delta: δ}, {epsilon: ε}, {eta: η}, {gamma: γ}, {iota: ι}, {kappa: κ}, {lambda: λ}, {mu: μ}, {nu: ν}, {omega: ω}, {omicron: ο}, {phi: φ}, {pi: π}, {psi: ψ}, {rho: ρ}, {sigma: σ}, {tau: τ}, {theta: θ}, {upsilon: υ}, {xi: ξ}, {zeta: ζ}]
---
matches:
{{- range $trigger, $replace := .greek_alphabet }}
  - trigger: ":{{ $trigger }}"
    replace: "{{ $replace }}"
    propagate_case: true
{{- end }}
```

I can't really think of why one might want to render files containing frontmatter in Chezmoi, but this may necessitate a source attribute.

## Describe alternatives you've considered
I can of course define most of these data types in the go template system directly but its syntax is tortured for many data types.

I've got it in a `greek_alphabet.yaml` file in the `.chezmoidata` directory, which keeps it mostly clean. I did run into an issue with trying to colocate a `.chezmoidata.yaml` in the same directory as the template usage -- `chezmoi execute-template` could find it, but `chezmoi apply` couldn't see the information from that file.

**Comment by halostatue** [comment]
Would this work, @twpayne?

```
# test that chezmoi apply sees .chezmoidata files in a subdirectory
exec chezmoi apply
cmp $HOME/.dir/file golden/file

# test that chezmoi execute-template sees .chezmoidata files in a subdirectory
stdin $CHEZMOISOURCEDIR/dot_dir/file.tmpl
exec chezmoi execute-template
cmp stdout golden/file

-- golden/file --
key value
-- home/user/.local/share/chezmoi/.chezmoidata.yaml --
old: key
-- home/user/.local/share/chezmoi/dot_dir/.chezmoidata.yaml --
key: value
-- home/user/.local/share/chezmoi/dot_dir/file.tmpl --
{{ .old }} {{ .key }}
```

**Comment by twpayne** [comment]
This should work. If it doesn't then it's a bug in chezmoi. Trying your test now...

**Comment by twpayne** [comment]
...and this test passes for me.

**Comment by zacwest** [comment]
I can think of another option: `frontmatter_file.tmpl` This would allow you to know _for sure_ how to parse the frontmatter part without having to inspect the file.

But I totally understand your reasoning too.

Here's the error I get:

```
> chezmoi diff
chezmoi: template: private_dot_config/private_espanso/match/greek.yml.tmpl:6:32: executing "private_dot_config/private_espanso/match/greek.yml.tmpl" at <.greek_alphabet>: map has no entry for key "greek_alphabet"
```

but:

```
> chezmoi execute-template <private_dot_config/private_espanso/match/greek.yml.tmpl
# `propagate_case` allows e.g.:
# alpha^ => α
# ALPHA^ => Α [or Alpha^ since it's just 1 char]

matches:
  - trigger: "alpha^"
    replace: "α"
    propagate_case: true
# <snip>
```

Could it be the depth that I'm creating at? 

Full files:

`greek.yml.tmpl`
```yaml
# `propagate_case` allows e.g.:
# alpha^ => α
# ALPHA^ => Α [or Alpha^ since it's just 1 char]

matches:
{{- range $trigger, $replace := .greek_alphabet }}
  - trigger: "{{ $trigger }}^"
    replace: "{{ $replace }}"
    propagate_case: true
{{- end }}
```

`.chezmoidata.yaml`
```yaml
greek_alphabet:
  alpha: α 
  beta: β
  chi: χ
  delta: δ
  epsilon: ε
  eta: η
  gamma: γ
  iota: ι
  kappa: κ
  lambda: λ
  mu: μ
  nu: ν
  omega: ω
  omicron: ο
  phi: φ
  pi: π
  psi: ψ
  rho: ρ
  sigma: σ
  tau: τ
  theta: θ
  upsilon: υ
  xi: ξ
  zeta: ζ
```
