### ISSUE TITLE
bug: `promptStringOnce` does not accept `--promptString` defaults

### ISSUE THREAD

**Issue by gabyx** [twpayne/chezmoi#3345]
## Describe the bug

`promptStringOnce` does not accept `--promptString` defaults:

a `chezmoi.yaml.tmpl`

```yaml
{{- $workspace := promptStringOnce "Set the workspace [private|work]" "private" -}}
data:
  workspace: {{ $workspace }}
```
and

```shell
chezmoi init -C test.yaml -S ~/test-dir --prompt --promptString variable=bla
```

Does still prompt eventhough it should not.

## To reproduce

Place the file `.chezmoi.yaml.tmpl` inside `~/test-dir` and 
Run `chezmoi init -C test.yaml -S ~/test-dir --prompt --promptString variable=bla`

## Expected behavior

The command should run non-interactive.

## Output of command with the `--verbose` flag

It prompts the user for the `workspace` variable.
