### ISSUE TITLE
Supports predefined configuration file paths, shares the fruits of labor, and saves a lot of time!

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [twpayne/chezmoi#3370]
look at [mackup](https://github.com/lra/mackup/tree/master/mackup/applications)

Just add an applications folder and accept contributions from the community

git.toml
```toml
windows = [ ".gitconfig" ]
macos = [ ".gitconfig" ]
linux = [ ".gitconfig" ]
```

The chezmoi init command needs to add a logic to traverse the applications folder to obtain all definitions, then obtain the definitions of the current system, traverse it, and perform operations similar to chezmoi add on the path.
