### ISSUE TITLE
chezmoiexternals conflict

### ISSUE THREAD

**Issue by davidolrik** [twpayne/chezmoi#3409]
I'm trying to install the Helix editor using the precompiled version found on GitHub.

I have also added the helix config to my  chezmoi repo.

These are the helix files chezmoi controls:
```
dot_config/helix
├── config.toml
└── themes
    └── my_theme.toml
```

This external will include the helix runtime directory in `.config/helix/runtime`
```
[".config/helix"]
  type = "archive"
  url = "https://github.com/helix-editor/helix/releases/download/23.10/helix-23.10-aarch64-macos.tar.xz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = [ "helix-23.10-aarch64-macos/runtime/**" ]
```

Unfortunately this conflicts with the state of `.config/helix` already added to chezmoi.

As a workaround I'm currently including the external using `[".config/helix/runtime"]` which installs the directory into `.config/helix/runtime/runtime`.

**Comment by twpayne** [comment]
Do you have a specific question?

**Comment by davidolrik** [comment]
I apologise if I haven't described the bug well enough, but given the that following two files are added to chezmoi:

- `.config/helix/config.toml`
- `.config/helix/themes/my_theme.toml`

It is impossible to extract the `runtime` directory and place it in `.config/helix/runtime`, as the external seems to be using the same state key: `.config/helix`.

This is the error I get when trying to apply the config above:

```sh
$ chezmoi apply --refresh-externals
chezmoi: .config/helix: inconsistent state (/Users/me/.local/share/chezmoi/dot_config/helix, https://github.com/helix-editor/helix/releases/download/23.10/helix-23.10-aarch64-macos.tar.xz defined in /Users/me/.local/share/chezmoi/.chezmoiexternal.toml)
```

It seems to me that the archive external should use whatever is in the `include` parameter as state keys, and not the actual path of the external - in this case `.config/helix` vs `.config/helix/runtime`.

Does that make sense?

**Comment by bradenhilton** [comment]
If I'm not mistaken, this should do what you want:

`dot_config/helix/.chezmoiexternal.toml`:

```toml
["runtime"]
  type = "archive"
  url = "https://github.com/helix-editor/helix/releases/download/23.10/helix-23.10-aarch64-macos.tar.xz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["helix-23.10-aarch64-macos/runtime/**"]
```
