### ISSUE TITLE
package installer for the external directive

### ISSUE THREAD

**Issue by dhruvinsh** [twpayne/chezmoi#3454]
## Is your feature request related to a problem? Please describe.

If possible, it would be good idea to support the package installer to the `.chezmoiexternal` directive. It could be something superficial like,

## Describe the solution you'd like
An external directive could look like as,

```yaml
name: # this use to indicate path but it doen't matter any longer, could be use as indication a package download location
  type: package
  url: https://github.com/sharkdp/bat/releases/download/v{{ .batVersion }}/bat-musl_{{ .batVersion }}_{{ .chezmoi.arch }}.deb
  manager: apt # various manager can be provide, yum, apt, pacman, winget with flags
```

here since we are dealing with externally build packages only, URL is must, else for the built in automated packages one must have to relies back to script.
 
## Describe alternatives you've considered

Right now easy implementation is OS specific shell script, Above directive would be much cleaner.
