### ISSUE TITLE
Prevent chezmoi external deleting something.

### ISSUE THREAD

**Issue by dngray** [twpayne/chezmoi#3549]
## What exactly are you trying to do?

I'm using asdf as a chezmoi external:

```toml
[".asdf"]
    type = "archive"
    url = "https://codeload.github.com/asdf-vm/asdf/tar.gz/refs/tags/v0.14.0"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
```

It downloads fine, and installs everything, then I have `.chezmoiscripts/run_once_after_90-asdf.sh.tmpl`

```bash
#!/bin/sh

asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs latest

asdf plugin-add rust https://github.com/asdf-community/asdf-rust.git
asdf install rust latest

asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git
#asdf global deno latest
```

This installs files into `~/.asdf/installs/`. However the next time chezmoi runs it sees the home dir has changed and removes the `installs` directory.

What would be a way to prevent this from happening?
