### ISSUE TITLE
Add a `gitHubLatestReleaseAsset` function

### ISSUE THREAD

**Issue by joshuaspence** [twpayne/chezmoi#3725]
## Is your feature request related to a problem? Please describe.

Whenever I use the `githubLatestRelease` function I need to do some additional processing in order to make use of the return value. Most commonly I end up doing something like this:

```yaml
---
.local/bin/chezmoi:
  type: 'file'
  executable: true
  url: '{{ (gitHubLatestRelease "twpayne/chezmoi").HTMLURL | replace "/releases/tag/" "/releases/download/" }}/chezmoi-{{ .chezmoi.os }}-{{ .chezmoi.arch }}'
```

This works but isn't as readable as I'd like.

## Describe the solution you'd like

A new `githubLatestReleaseAsset` function which can be used to select an asset with a given name (or perhaps matching a glob) from the latest release. For example:

```yaml
.local/bin/chezmoi:
  type: 'file'
  executable: true
  url: '{{ gitHubLatestReleaseAsset "twpayne/chezmoi" (printf "chezmoi-%s-%s" .chezmoi.os .chezmoi.arch ) }}'
```

## Describe alternatives you've considered

Alternatively I could define my own helper template functions, which would be nice for other reasons.
