### ISSUE TITLE
Documentation update "Why do I get a blank buffer or empty file when running chezmoi edit"

### ISSUE THREAD

**Issue by SjoerdV** [twpayne/chezmoi#3815]
Proposed update for:
https://www.chezmoi.io/user-guide/frequently-asked-questions/troubleshooting/#why-do-i-get-a-blank-buffer-or-empty-file-when-running-chezmoi-edit

Maybe you could add a tab (next to VIM/VSCode tabs) to get **Any editor** (also the ones that do not wait in the foreground) to work with `chezmoi edit`

1. Add a new bash program somewhere in your $PATH (in this case I added `$HOME/.local/bin/mousepad-wait`)
```bash
#!/usr/bin/env bash
wait -n; mousepad "$@"
```
1. Run `chmod +x $HOME/.local/bin/mousepad-wait` to make the program executable
1. Finally add to (or update) `chezmoi.toml`
```toml
[edit]
    command = "mousepad-wait"
    args = ["--opening-mode=window", "--encoding=UTF-8"]
```
