### ISSUE TITLE
Feature requeset: Get external from commands

### ISSUE THREAD

**Issue by Ra2-IFV** [twpayne/chezmoi#3972]
## Is your feature request related to a problem? Please describe.

I was trying to let `chezmoi` manage something that comes from commands. (bash completions, or process commands like `grep` `jq` `sed`)

## Describe the solution you'd like

Add a new external `type`: `command`

## Describe alternatives you've considered

Create a script, but it won't has features in [.chezmoiexternal](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/)

## Additional context

Not sure if it's a good idea.

**Comment by halostatue** [comment]
Can you write up something that describes what such an external would look like?

**Comment by Ra2-IFV** [comment]
```toml
["~/.local/share/bash-completion/completions/chezmoi.bash"]
    type = "command"
    command= "/usr/local/bin/chezmoi"
    args = ["completion", "bash"]
    refreshPeriod = "168h"
```
