### ISSUE TITLE
git-repo external and umask don't play nice

### ISSUE THREAD

**Issue by hugoh** [twpayne/chezmoi#4214]
## Describe the bug

With `umask = 0o077`, a `git-repo` external refresh always believes that the destination copy has changed. 

## To reproduce

I have the following external defined:

```toml
[".vim/pack/chezmoi/start/chezmoi.vim"]
  type = "git-repo"
  url = "https://github.com/alker0/chezmoi.vim.git"
  refreshPeriod = "168h"
  clone.args = ["--depth", "1"]
  pull.args = ["--ff-only"]
```

With the following in the config:

```toml
umask = 0o077
```

`cm apply -R .vim/pack/chezmoi/start/chezmoi.vim` will always say: `.vim/pack/chezmoi/start/chezmoi.vim has changed since chezmoi last wrote it?`:

```
~ ❯ chezmoi apply -R .vim/pack/chezmoi/start/chezmoi.vim 
.vim/pack/chezmoi/start/chezmoi.vim has changed since chezmoi last wrote it? overwrite/all-overwrite/skip/quit
```

Overwriting and running it again will produce the same outcome again.

Removing the `umask` setting fixes the problem.

## Expected behavior

```
~ ❯ chezmoi apply -R .vim/pack/chezmoi/start/chezmoi.vim 
Already up to date.
```

## Output of command with the `--verbose` flag

Same.
