### ISSUE TITLE
chezmoidata files merge only dictionaries

### ISSUE THREAD

**Issue by halostatue** [twpayne/chezmoi#4309]
## Describe the Problem

This is only partially documented with [changes made recently](https://www.chezmoi.io/reference/special-directories/chezmoidata/) because the data in the files files will be deep merged if the structure is a map, but will *not* be merged if the values are lists.

I have been working on a major change to how software packages are managed from within chezmoi and found a limitation in the structures because I am building in conditional installation features. It'll all be visible from my public repo soon enough, and it's probably overkill, but it's a good mental exercise if nothing else.

## To reproduce

- **.chezmoidata/one.yaml**:
   ```yaml
   test:
     x:
       y:
         a: 1
     cond:
       - if: true
   ```

- **.chezmoidata/two.yaml**:
   ```yaml
   test:
     x:
       y:
         b: 2
     cond:
       - if: false
   ```

Then run:

```console
$ chezmoi data | jq .test
{
  "test": {
    "x": {"y": {"a": 1, "b": 2} },
    "cond": [{ "if": false }]
  }
}
```

## Expected behaviour

Not sure. I'm working around this by unifying multiple files that merged the same dictionary into one value, but it would be _cleaner_ if I didn't have to do so. Once unified, though, I probably won't want to split it back apart.

There are two choices:

1. We ensure that the deep merging of data crosses lists.
2. We document that only dictionaries are merged.

Having just written the documentation that talks about the dictionary merging, I think it might be easier to deep merge lists. I'm only half kidding.

**Comment by twpayne** [comment]
This is a tricky problem. I don't think there's any well-defined algorithm for merging values. The current behavior happens to be less surprising with dictionaries compared to other types, but that is by accident rather than design.

Some thoughts:

* Merging dictionaries can have the reasonable behavior of (1) new keys that aren't present set a new key/value pair in the dictionary, (2) new keys that are already present overwrite the existing key/value pair.
* Merging lists have a multitude of options: replace, append (old or new value first?), interleave? sort?
* Merging simple values have a multitude of options: should integers add or multiply or replace? should strings concatenate? should bools merge with AND, OR, or XOR?

I don't think that there are any good answers here. chezmoi currently updates dictionaries with a replace-or-add strategy ([code here](https://github.com/twpayne/chezmoi/blob/882696f778d1e186d17cf9460a14e77d601a6d21/internal/chezmoi/recursivemerge.go).

**Comment by halostatue** [comment]
That's why I said that the choice is either to merge lists or to document the replace-or-add strategy as it applies to dictionaries and indicate that anything *other* than dictionaries is always replace.

I would *prefer* to merge lists, as I think that would be least surprising for my use case, but my use case is also not every use case.

**Comment by twpayne** [comment]
> I would _prefer_ to merge lists, as I think that would be least surprising for my use case, but my use case is also not every use case.

But merge lists how? Append (in which order?)? Interleave? Sort and remove duplicates? There is no clear correct answer here.

**Comment by ebrusseau** [comment]
I have the same use case.  The map merging as you describe with a value of true/false as a conditional to install or not for software packages., but with more complex concepts like inserting dock items in order for example, they won't as the keys are always sorted lexically.  The issue I think is that we have very limited sorting options.

To further illustrate the issue, the following code can easily be merged with other sources also supplying items to dock.apps, but the result is always sorted by the keys, so the order will not be correct.  Adding a position attribute to each app doesn't do any good as there is no real way to use it to accomplish a properly sorted set.

``` yaml
dock:
  apps:
    Safari:
      path: /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
      position: 0
    Ghostty:
      path: /Applications/Ghostty.app
      position: 1
```

The following option of course preserves the order, but things get tricky if you manually merge other sources with the dock.apps list with concat, as the order is the desired order is likely not valid.  If there was an ability to sort a list with an items' key, this would solve the issue, as once concat'ed you could simply use something like `{{ $sortedApps := sort $mergedApps position }}` in your template to convert the merged lists into the correct order.  I believe Gomplate has this ability, but sadly we do not at the moment.

```yaml
dock:
  apps:
    - label: Safari:
      path: /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app
      position: 0
    - label: Ghostty
      path: /Applications/Ghostty.app
      position: 1
```
