### ISSUE TITLE
Add environment variable for password manager commands

### ISSUE THREAD

**Issue by chuxubank** [twpayne/chezmoi#4324]
## Is your feature request related to a problem? Please describe.

When I first time run `chezmoi init <username> -a` in a new machine, I want to use `pass` to fulfill some of the contents in templates.
But my `PASSWORD_STORE_DIR` is set to a place other than the default one `~/.password-store`.
So even if I clone the repo to the `PASSWORD_STORE_DIR` in `hooks.read-source-state.pre`, since the environment variable is not set at that time, the `pass` command will not found the repo and report error.

## Describe the solution you'd like

Add a environment variable field for [pass] in `.chezmoi.toml.tmpl`, so pass will execute with that environment variable?

## Describe alternatives you've considered

First clone repo to default path `~/.password-store`, then move it to the `PASSWORD_STORE_DIR`.

**Comment by halostatue** [comment]
This is already supported.

```toml
[scriptEnv]
PASSWORD_STORE_DIR = "~/not-password-store"

[hooks.read-source-state.pre]
command = "bash"
args = ["-c", "echo $PASSWORD_STORE_DIR"]
```
