### ISSUE TITLE
Pager ignored when using "diff" as diff.command

### ISSUE THREAD

**Issue by SickMcNugget** [twpayne/chezmoi#4500]
## Describe the bug
(v2.62.6)
When setting the diff command in chezmoi.toml to "diff" explicitly, the pager provided is ignored.

## To reproduce

edit `chezmoi.toml`
```toml
[diff]
    command = "diff"
    pager = "less -R"
```

## Expected behavior

The output of diff should be piped into less.

## Additional context

I'm not just arbitrarily trying to change the command to diff with no other changes. The actual toml I'd like to end up with is:
```toml
[diff]
    command = "diff"
    args = ["--color=always", "-u", "{{ .Target }}", "{{ .Destination }}"]
    pager = "less -R"
```
since I prefer to have target before destination, and I find the colouring easier to grok with this output.

**Comment by SickMcNugget** [comment]
Here's a little txtar test I've made to show that it doesn't work properly.

`issue4500.txtar`
```
cat internal/cmd/testdata/scripts/issue4500.txtar
[windows] skip 'UNIX only'

chmod 755 bin/custom-pager

# test that chezmoi diff does invoke the diff pager when there is a diff and the command is not "diff"
cp golden/dot_file $CHEZMOISOURCEDIR
exec chezmoi diff
stdout custom-pager

chhome home2/user

# test that chezmoi diff does invoke the diff pager when there is a diff and the command is "diff"
cp golden/dot_file $CHEZMOISOURCEDIR
exec chezmoi diff
stdout custom-pager

-- golden/dot_file --
# contents of .file
-- bin/custom-pager --
#!/bin/sh

echo custom-pager
-- home/user/.config/chezmoi/chezmoi.toml --
[diff]
    pager = "custom-pager"
-- home2/user/.config/chezmoi/chezmoi.toml --
[diff]
    command = "diff"
    pager = "custom-pager"
-- home/user/.local/share/chezmoi/.keep --
-- home2/user/.local/share/chezmoi/.keep --

```

**Comment by twpayne** [comment]
Thank you very much for the test case. There's definitely a bug here. I'm investigating in https://github.com/twpayne/chezmoi/compare/fix-4500.

**Comment by twpayne** [comment]
So I did a bit more investigating. I don't have a fix yet, but I think I understand what's going on. My understanding is:

* chezmoi allows you to configure an external diff tool through the `diff.command` and `diff.args` configuration variables.
* chezmoi allows you to configure a diff-specific pager through the `diff.pager` configuration variable.
* External diff tools work in multiple different ways:
  * They can take two filenames as arguments, or take no arguments and read a an existing diff from stdin and reformat it.
  * They may or may not take control of the terminal and page the output.
 
chezmoi currently assumes that if you're using an external diff tool then that diff tool is also responsible for paging, so if you have `diff.command` set then chezmoi explicitly ignores `diff.pager`. This assumption is obviously incorrect in the case demonstrated here.

I suspect that the solution is to always pipe the diff output (whether from chezmoi's internal diff or the external `diff.command` if set) into `diff.pager` if `diff.pager` is set. This is also related to #3523.

I'm working on a PR.

**Comment by twpayne** [comment]
Would you be able to test #4584?

**Comment by SickMcNugget** [comment]
Ran `go test` on everything, seems to work on my machine. I also built chezmoi, initialised a test repo and added a real file. That seemed to work, too. 

With this `chezmoi.toml`, I got coloured output that was paged with less (when the output required it).
```toml
[diff]
    command = "diff"
    args = ["--color=always", "-u", "{{ .Target }}", "{{ .Destination }}"]
    pager = "less -R"
```

With this `chezmoi.toml`, I got coloured output that was just sent to terminal without paging.
```toml
[diff]
    command = "diff"
    args = ["--color=always", "-u", "{{ .Target }}", "{{ .Destination }}"]
```

My testfile was very simple:
```
--- /tmp/chezmoi-diff3824887299/work/chezmoi/testfile   2025-08-05 22:41:37.760039052 +0800
+++ /dev/null   2025-03-16 19:20:00.817000093 +0800
@@ -1,1001 +0,0 @@
-newthings
-newthings
-newthings
-newthings
-newthings
...etc
```

All in all it seems like you've solved it, thanks for making the time.

**Comment by twpayne** [comment]
Awesome, thank you very much for the comprehensive testing!

**Comment by larsgerber** [comment]
I use https://github.com/Wilfred/difftastic with the following configuration as a diff tool.
```toml
[diff]
command = "difft"
args = ["--display", "side-by-side"]
reverse = true
```

This configuration does show me all diffs below each other with syntax highlighting enabled.

This behavior changed after version [v2.64.0](https://github.com/twpayne/chezmoi/releases/tag/v2.64.0). Now I have to exit the pager to show the next file and the syntax highlighting stopped working.

Here are the configuration changes required to return to the old behavior, in case anyone is looking for it.

```toml
[diff]
command = "difft"
args = ["--display", "side-by-side"]
reverse = true
pager = ""
```

If someone only wants to restore the syntax highlighting, the following configuration can be used.

```toml
[diff]
command = "difft"
args = ["--display", "side-by-side", "--color", "always"]
reverse = true
```
