### ISSUE TITLE
chezmoi data file does not exist

### ISSUE THREAD

**Issue by truesilver92** [twpayne/chezmoi#550]
When running `chezmoi -v data` or `chezmoi data` chezmoi comes back
with 

`chezmoi: file does not exist`

I was just trying to have chezmoi print out the json data that my
templates can use. It was a way to check that my changes to
`.config/chezmoi/chezmoi.toml` are working correctly (well actually my
changes to `.chezmoi.toml.tmpl`)

I used `chezmoi init` to test the template for the config file, and the config file it generated looks fine to me (edited for privacy)

```toml
# -*- mode: conf-unix; -*-






[data]
    email = "j@example.com"
    gpg_default_key = "9A"
    vm = "y"
    wayland = "n"
```

Any advice for figuring out which file chezmoi can't find?
