### ISSUE TITLE
merge existing .chezmoi.toml in init command

### ISSUE THREAD

**Issue by raffomania** [twpayne/chezmoi#570]
## Is your feature request related to a problem? Please describe.

When I update my `.chezmoi.toml.tmpl` and add a key, I run `chezmoi init` to update my config file. I then have to re-enter every configuration key, even if they are already present in the config file.

## Describe the solution you'd like

I'd like to be prompted for only the configuration keys not already present in my config file.

## Describe alternatives you've considered

A possible workaround would be to manually edit my template to only prompt for a config value if it is not already set. I would like it better if `promptString` had this built in, though.

**Comment by raffomania** [comment]
Just tried to implement the described workaround, but values from chezmoi.toml don't seem to be available in `.` when the template is rendered :(

**Comment by twpayne** [comment]
Thanks for the suggestion. `chezmoi init` was envisaged to only be ever run once per machine, and I didn't anticipate using it to re-generate chezmoi's config file. I personally only have three data fields in my config, so updating the config file manually on each machine when needed is not too onerous for me. If you have a lot of data fields that are also changing regularly, then I can see how it would be bothersome.

I think there is a possible solution, but need to think this through:

1. Manage chezmoi's config file with chezmoi itself (i.e. `chezmoi add --template ~/.config/chezmoi/chezmoi.toml`).

2. Add a `promptStringIfAbsent` which takes a key and a prompt. If the key already exists in `.` then it returns its value, otherwise it prompts for a value and returns that.

3. In `chezmoi init`, if there is an existing config file, then make its data available in `.` when generating the initial config file.

However, this seems quite complicated, and I'd like to keep things simple, if possible.

Could you post your `.chezmoi.toml.tmpl` to help me understand?

**Comment by raffomania** [comment]
My config template looks like this:
```toml
{{- $type := promptString "machine type (desktop|laptop)" -}}
{{- $hidpi := promptString "is hidpi? (true|false)" -}}
{{- $eth_device := promptString "ethernet device name" -}}
{{- $wifi_device := promptString "wifi device name (leave empty if none)" -}}
[data]
    machine_type = "{{ $type }}"
    hidpi = {{ $hidpi }}
    eth_device = "{{ $eth_device }}"
    wifi_device = "{{ $wifi_device }}"
    two_batteries = false
```
I guess once I'm finished converting my dotfiles to templates the pain of updating the config file will not be too large, but of course I have the itch to automate every task I can :) So if you think this adds too much complexity, definitely go ahead and close the issue.
I think step 1 and 3 kind of contradict each other, though? If I managed chezmoi's config with the regular chezmoi, a simple `chezmoi apply` would be enough to update it without `init`?
