### ISSUE TITLE
Variant from a template

### ISSUE THREAD

**Issue by cljoly** [twpayne/chezmoi#749]
## What exactly are you trying to do?

Some software don't support inclusion of configuration file. For example, if you want to have two different fonts in Alacritty, you need to create two identical configurations, with just the font size varying. Another example would be with i3 and sway window manager: some of the configuration syntax is common between them and this could be leveraged to share part of the configuration.

For instance, the base file would be like:
``` yml
some: config
fontsize: {{ .size }}
somemore: config
```

And then, `small-font.yml` would be
``` yml
some: config
fontsize: 12
somemore: config
```

And, `big-font.yml` would be
``` yml
some: config
fontsize: 18
somemore: config
```

I would like a way to generate `big-font.yml` and `small-font.yml` from the base file.

## What have you tried so far?

I tried to generate a base go template and to call it from two other files with a variable set (for instance, the font size), to create the two configurations identical except for the font size.

## Where else have you checked for solutions?

* [X] I have read [chezmoi's how-to
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not
  found the answer.
* [X] I have read [chezmoi's
  FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not
  found the answer.
* [X] I have searched [chezmoi's reference
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and
  not found the answer.
* [X] Other, please give details.

## Additional context

this might be achievable with scripting, but 1) this might slow down chezmoi and 2) it would move away from the declarative approach.

I'm that this kind of feature light be out of scope of the project. I'm just wondering if there is a good way to achieve what I describe within current features.

**Comment by cljoly** [comment]
Thank you so much for your explanations!

I noticed that passing a dictionary to the template works:
``` yml
some: config
fontsize: {{ .fontsize }}
font: {{ .font }}
somemore: config
```
And then
``` yml
{{- template "alacritty" dict "fontsize" 12 "font" "Iosevka" -}}
```
