### ISSUE TITLE
Select which files to sync on chezmoi config

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#845]
## Description

Currently, if I don't want to sync a bash script conditionally, I have to make it a `.tmpl` and wrap the entire content of the file in a template expression, such as: 

`executable_hello_world.sh`
```bash
{{ if .is_wsl - }}
echo "Hello World!"
{{ end -}}
```

The downside is: 
- My editor stop understanding the file content as shell script because it has now a `.tmpl` extension.
- My linter (`shellcheck`) freaks out because `{{ if .is_wsl - }}` is not a valid bash statement.
- I can not easily share this `executable_hello_world.sh.tmpl` to other people using a GitHub URL because the file is not actually a script and must be parsed by `chezmoi` first.

The real example is here: https://github.com/felipecassiors/dotfiles/blob/master/dot_local/bin/executable_docker.tmpl

## Solution

1. Have my script anywhere I want in the repository, such as: `scripts/hello_world.sh`.
2. Add it to `.chezmoiignore`.
3. In `.chezmoi.yaml.tmpl` I could have something like:

    ```yaml
    {{- $isWsl := not (not (or (env "WSL_DISTRO_NAME") (env "IS_WSL"))) -}}
  
    sync:
      {{ if .is_wsl - }}
      scripts/hello_world.sh:
        destination: ~/.local/bin/
        permissions: executable
      {{ end -}}
    ```
